### PR TITLE
feat: Add Fedora packaging via packit

### PR DESCRIPTION
**Pull request by LecrisUT**
See https://github.com/cp2k/dbcsr/pull/759

Depends on: https://github.com/cp2k/dbcsr/pull/759

### CODE REVIEW

**Comment by oschuett** [comment]
I'm not sure about this PR.

Since CP2K is included in [many distributions](https://www.cp2k.org/download#from_an_official_release), I'd really prefer to keep the clear separation between upstream and downstream code. In fact, we've just moved our production containers into [their own repository](https://github.com/cp2k/cp2k-containers) for that very reason.

What do you think @rathann?

**Comment by rathann** [comment]
I stepped down as package maintainer of cp2k in Fedora and @LecrisUT is the new maintainer. If you don't want to add Fedora-specific stuff, that's fine. We can keep it downstream only as well.

**Comment by LecrisUT** [comment]
Thanks @rathann for clarifying that.

I would mention a few points to try to explain my reasoning for proposing this:
- Fedora has a very comprehensive CI testing framework, testing both while building and after installation
- This integration allows upstream developers to know early of any changes in other projects (from Fedora rawhide) that will eventually affect this project when a new release is made
- On the projects that I help package, I provide a [`nightly`](https://copr.fedorainfracloud.org/coprs/lecris/nightly/) and [`release`](https://copr.fedorainfracloud.org/coprs/lecris/release/), which can be used to know of any changes that are made in the `main` branch and release tags respectively
- Testing for packaging compatibility and keeping up to date will be much easier when there is access to the source-code to experiment with
- Packaging tests can be rather tricky requiring coordination between the `cp2kConfig.cmake` files and the tests

What @rathann says about keeping it downstream is correct, we can integrate packit completely donwstream as well, but:
- If using downstream only, issues are only spotted post-release, requiring making patches downstream to fix things. Having this build in upstream will pick up any issues early, and so that other downstream can benefit from these
- If we provide a working and maintained reference `.spec` file, any downstream packagers can use it to reference how to build and package, what variants to provide, etc.

**Comment by oschuett** [comment]
> I stepped down as package maintainer of cp2k in Fedora and @LecrisUT is the new maintainer.

Thank you @rathann for your many years of faithful support!
And @LecrisUT thank you for taking over!

> Fedora has a very comprehensive CI testing framework, testing both while building and after installation

That's a great point and I'm actually a big fan of testing. And in fact, we already run a [test for Fedora](https://dashboard.cp2k.org/archive/fedora-psmp/index.html) on a weekly basis.

However, I think we should be careful not to couple our two projects too tightly. Specifically, I'd like to avoid hosting a full full copy the Fedora package and neither do I want CP2K to depend on Fedora's test infrastructure.

So, I'd propose that we instead improve our [existing test](https://github.com/cp2k/cp2k/blob/master/tools/docker/Dockerfile.test_fedora-psmp) to better cover the risks of the downstream packaging.

What do you think?

**Comment by LecrisUT** [comment]
>  I'd like to avoid hosting a full full copy the Fedora package

This PR is all the Fedora project files. Actually this one also includes tests, abd the minimum is actually just 2 files `.packit.yaml`, `cp2k.spec`.

> neither do I want CP2K to depend on Fedora's test infrastructure

Of course there will be no dependencies, these are just additional build tests that will help the packagers keep track of changes upstream and offer upstream patches in a timely manner.

> So, I'd propose that we instead improve our [existing test](https://github.com/cp2k/cp2k/blob/master/tools/docker/Dockerfile.test_fedora-psmp) to better cover the risks of the downstream packaging.

This is tricky because the purpose of the CI tests there are orthogonal with the packaging tests introduced here.
- In those tests, `cp2k` is built manually based on a branched Fedora environment, but what we need to test is that:
  - `rpm` build with the Fedora standard flags are working correctly
  - After build, if we install the cp2k rpm, the tests still function correctly
  - We need to test `rawhide` as often as possible. Dockerfiles would not be appropriate because it would cache the `FROM` image
- The minimum tests to pass are the unit-tests, but regression tests are also welcome, but it is encouraged to use `testing-farm` for those instead
- RPM tests change very often. Instead we provide a format where upstream does not have to maintain such tests, e.g. if you see `rpminspect.fmf`, it simply point to `main` branch of a repository, and all maintenance is done upstream.
- Packaging tests are tricky in that they depend on each environment, and it would be better to be over-complete in how/where you test it. E.g. in [spglib](https://github.com/spglib/spglib) project, we test 3 different variants of consuming the project (`FetchContent`, `find_package`, `pkg-config`), on all environments that allow us to run tests (even 5 times in Fedora environments), and we do occasionally find packaging issues that need to be addressed, like when we changed `SOVERSION` in `spglib` and had to coordinate with `cp2k` packaging to update.

And in case there is such concern, I want to assure that I can adjust these tests depending on the level of integration that you desire, from only making a PR to src.fedoraproject.org for each release, to collaboratively working on fixes with upstream. And even in the maximally integrated form there will not be PR spams about Fedora backend maintenance changes

**Comment by oschuett** [comment]
Thank you very much for the long explanation and sorry for the (again) late reply . Let's try to unpack this a bit.

**Code location**: I really believe that Fedora code should live in a Fedora repository because that's where the Fedora community is. Here on the CP2K repository, no one is qualified to review changes and no one can pick up the pieces if anything goes wrong. Ultimately it's a question of ownership and I really don't think that the CP2K developers should own the Fedora package.

**Testing by Fedora**: Nothing is preventing you from running tests against CP2K's master branch on a regular basis. To make our developers aware of the results of such tests, we could list them on our [dashboard](https://dashboard.cp2k.org).

**Testing by CP2K**: Building and testing CP2K is actually fairly expensive. We can offer to run a weekly test on our infrastructure, which is paid for by the CP2K Foundation. Please don't let the current setup put you off. We can rewrite that Dockerfile to anything you like. It could e.g. begin with:

```
FROM fedora:rawhide
RUN yum -y update
```

What do you think?

**Comment by LecrisUT** [comment]
> Code location: I really believe that Fedora code should live in a Fedora repository because that's where the Fedora community is. Here on the CP2K repository, no one is qualified to review changes and no one can pick up the pieces if anything goes wrong. Ultimately it's a question of ownership and I really don't think that the CP2K developers should own the Fedora package.

I want to clarify the point here. Adding these files would not mean that Fedora packagers will now have to write changes to this repo, and especially **not** that cp2k would now be responsible for doing fixes to the Fedora package. The Fedora package continues to be managed independently.

As I've said the integration here is very flexible and the only integration I am recommended to add here (which again, the backend is not managed by cp2k, and the only overhead for cp2k is to ping me when build/tests fail):
- push PRs to fedoraproject upon new releases
- run test builds on releases/master/prs

> Testing by Fedora: Nothing is preventing you from running tests against CP2K's master branch on a regular basis. To make our developers aware of the results of such tests, we could list them on our [dashboard](https://dashboard.cp2k.org/).

Within the Fedora infrastructure, that is not possible because it cannot listen to all commits for all git repositories. Instead the projects install webhooks to push notifications when new commits are done, and that is what this PR is all about, to enable that infrastructure with packit.

> Testing by CP2K: Building and testing CP2K is actually fairly expensive. We can offer to run a weekly test on our infrastructure, which is paid for by the CP2K Foundation. Please don't let the current setup put you off. We can rewrite that Dockerfile to anything you like. It could e.g. begin with:

This does not account for the nuances of:
- `rawhide` package updates (there are multiple sources `copr`, `koji`, etc.). These are all handled behind the scenes by tools like `packit`
- build from source vs packaged version. The goal is to test the latter, and **not** the former. The latter would require to keep a `cp2k.spec` file to have the instructions of how to build the project as a `rpm` package. At which point there would be a much higher maintenance overhead, than using `packit` service which handles all of the nuance behind the scenes.

---

Ultimately this PR is a recommendation to keep the development of the Fedora package up to date with upstream (cp2k), and having such integration, will help immensely to keep the cp2k project from being removed from Fedora (which it was previously scheduled to be) due to the lack of packager's time to work both on patching the Fedora package, and work with the upstream developers on those patches.

**Comment by oschuett** [comment]
>  Instead the projects install webhooks to push notifications when new commits are done,...

I didn't realize this would setup webhooks. I've now read up a bit on packit. I assume you then want me to install the ["Packit-as-a-Service" GitHub application](https://github.com/marketplace/packit-as-a-service) ?

Isn't there a better way? Couldn't we use the [packit CLI](https://packit.dev/docs/cli) to trigger the builds via `packit build in-copr` from within our [CP2K-CI](https://github.com/cp2k/cp2k-ci). Any issues would then show up on our dashboard where they'd be reliably picked up by one of our core devs. It would provide a seamless integration for both of us.

Nevertheless, I can understand if you don't want a bespoke solution. I'd be ok with triggering packit jobs for commits and releases. However, I'm reluctant to enable them for pull requests because I don't think they will be very helpful at that point and mostly cause confusion.

As for the `.dist` directory, I still feel these files don't really belong into the upstream repository. Nevertheless, if there is no other way, then I'd propose we move them to `/tools/fedora/`.

**Comment by LecrisUT** [comment]
> Isn't there a better way? Couldn't we use the [packit CLI](https://packit.dev/docs/cli) to trigger the builds via packit build in-copr from within our [CP2K-CI](https://github.com/cp2k/cp2k-ci). Any issues would then show up on our dashboard where they'd be reliably picked up by one of our core devs. It would provide a seamless integration for both of us.

Good suggestion. Indeed that would work, but you would have to find a way to link to the copr dashboard on your end, and you would need my or someone's FAS credentials since it would no longer be authenticated by the packit bot account. One thing I cannot support in this model is to run the testing-farm tests which can do 2 things:
- Run rpmlint, inspect and other such rpm specific checks. These were very useful on spglib at one point to detect `SOVERSION` changes. These are not very crucial and I can add them downstream
- Run post-packaging tests. E.g. on spglib I have the `example` projects executed on the packaged version of the project. This would not be able to be done within the `.spec` file because those tests are done in the build tree

On the other hand I can discuss with the `packit` team if you would prefer a webhook model where the jobs are not posted on the GitHub interface, but instead are redirected to your servers for analysis.

> However, I'm reluctant to enable them for pull requests because I don't think they will be very helpful at that point and mostly cause confusion.

Understandable, I can adjust the integration to meet your requirements. It could be a bit more difficult when we need to collaborate on some bugs, but I can temporarily enable that feature when needed.

> As for the `.dist` directory, I still feel these files don't really belong into the upstream repository. Nevertheless, if there is no other way, then I'd propose we move them to `/tools/fedora/`.

Indeed, the minimum is to have a `.packit.yaml` in the root, and a `cp2k.spec` file. Folder structure it is indeed flexible and we can put it wherever you wish.

**Comment by oschuett** [comment]
> and you would need my or someone's FAS credentials

Unfortunately it turns out that the Copr API keys [expire after 180 days](https://copr.fedorainfracloud.org/api/). I don't want to renew it manually all the time. So then let's stay on the beaten path and use the Packit-as-a-Service app for now.

Could you make the two changes we discussed (move `.dist` to `/tools/fedora` and remove jobs for PRs)?

**Comment by LecrisUT** [comment]
> Unfortunately it turns out that the Copr API keys [expire after 180 days](https://copr.fedorainfracloud.org/api/).

You can use the kerberos identity, but beware that it has the full FAS identity. I wouldn't trust to put mine without properly reviewing the infrastructure.

> Could you make the two changes we discussed (move .dist to /tools/fedora and remove jobs for PRs)?

Sure

**Comment by LecrisUT** [comment]
Oh, yeah, there is no PR jobs, so `/packit build` will not do anything in the PR.

**Comment by oschuett** [comment]
Yeah, I just wanted to check if the bot is now watching our repo. Seems like it does :-)

**Comment by oschuett** [comment]
Apparently there is still a config issue on your side: https://github.com/cp2k/cp2k/runs/21521183606

**Comment by LecrisUT** [comment]
Yeah, forgot to set it up for cp2k, now it should be ok to re-trigger

(probably only a new push will trigger it though)

**Comment by oschuett** [comment]
I just discovered the [manual_trigger](https://packit.dev/docs/configuration/jobs#manual_trigger) option. That seems to fit our use case pretty well.

**Comment by LecrisUT** [comment]
Yes, that just disables the jobs from starting automatically and they can instead be triggered by `/packit build`. The PR job still needs to be configured to have effect. Should I add this.

BTW: some immediate issues that should be solved:
- Remove the `-Wall` from distro compilation
- Speed up the compilation (Ninja would help here)
- Remove the custom flags parsing. Fedora has its own flags that it passes

Do you want these addressed together in a single PR?

**Pull request merged**
