### PR TITLE
Try Intel Fortran compiler ifx instead of ifort

### PR DESCRIPTION
**Pull request by mkrack**
Switch completely from the Intel Classic compiler set icc/icpc/ifort to the new set icx/icpx/ifx provided by the Intel oneAPI HPC Toolkit 2023.0.0.

### CODE REVIEW

**Comment by mkrack** [comment]
Currently, the Intel Fortran compiler `ifx` from the oneAPI HPC Toolkit 2023.0.0 returns an Internal Compiler Error ([ICE](https://storage.googleapis.com/cp2k-ci/run-cp2k-intel-psmp-35f72912_report.txt)) in `dbcsr_tensor_types.F90`
```
error #5633: **Internal compiler error: segmentation violation signal raised** 
Please report this error along with the circumstances in which it occurred in a Software Problem Report. 
Note: File and line given may not be explicit cause of this error.
compilation aborted for dbcsr_tensor_types.F90 (code 3)
```
Separate tests reveal that the ICE disappears when the compiler flag `-qopenmp` is dropped whereas `qopenmp-simd` does not cause an ICE.

**Comment by oschuett** [comment]
@hfp, what would be the best way to report this to the Intel compiler team?

**Comment by oschuett** [comment]
Intel has released [version 2023.1.0](https://hub.docker.com/layers/intel/oneapi-hpckit/2023.1.0-devel-ubuntu22.04/images/sha256-1f628694fdadcfe47d632322011a2929704411ccda627f8f928365675f242528?context=explore) of their HPC Toolkit. Maybe this is worth another try?

**Comment by mkrack** [comment]
> Intel has released [version 2023.1.0](https://hub.docker.com/layers/intel/oneapi-hpckit/2023.1.0-devel-ubuntu22.04/images/sha256-1f628694fdadcfe47d632322011a2929704411ccda627f8f928365675f242528?context=explore) of their HPC Toolkit. Maybe this is worth another try?

Unfortunately, the Fortran compiler `ifx` of the new release 2023.1.0 still does not work.

**Pull request closed without merging**
