### PR TITLE
Toolchain: Add Dockerfile.cuda_mkl

### PR DESCRIPTION
**Pull request by oschuett**

### CODE REVIEW

**Comment by dev-zero** [comment]
btw, we should really be thinking about adding a linker exception to our license for CUDA, MKL, libsci, etc.

**Comment by oschuett** [comment]
The resulting docker image does indeed violate the GPL and must not be distributed. I added a warning message about that.

Nevertheless, I think this is exactly how the GPL is supposed to work. It reminds us that by using proprietary software we give up control which ultimately hurts science and business alike. The good news is that the industry seems to have realized and in a not too distant future we can hopefully do without.

**Comment by mtaillefumier** [comment]
Hi Ole,
We generate a second library when we compile sirius the split was introduced for an unknown reason (at least to me). [
[0001-Fix-SIRIUS-linking-issues-when-GPU-is-activated.txt](https://github.com/cp2k/cp2k/files/3365752/0001-Fix-SIRIUS-linking-issues-when-GPU-is-activated.txt)
](url)

this patch should fix the issue you have. I will ask to have this fixed in the next version. One library only is better

**Comment by oschuett** [comment]
Thanks @mtaillefumier !

**Comment by oschuett** [comment]
For some reason the JIT in libcusmm does not fill the gaps in the parameters. Hence, I'm switching the toolchain to `--gpu-ver=K20X` although this is running on a `K80`. Also, why is it using BLAS for `4x4x4`?

From  `H2O-ls-rtp.inp.out`:
```
 -------------------------------------------------------------------------------
 -                                                                             -
 -                                DBCSR STATISTICS                             -
 -                                                                             -
 -------------------------------------------------------------------------------
 COUNTER                                    TOTAL       BLAS       SMM       ACC
 flops     2 x     2 x     4                 3968       0.0%    100.0%      0.0%
 flops    13 x     2 x     4                 8736       0.0%    100.0%      0.0%
 flops     2 x    13 x     4                 8736       0.0%    100.0%      0.0%
 flops     2 x     4 x     2                11136       0.0%    100.0%      0.0%
 flops     4 x     4 x     2                14976       0.0%    100.0%      0.0%
 flops     2 x     4 x     4                19968       0.0%    100.0%      0.0%
 flops     2 x     2 x     2                21520       0.0%    100.0%      0.0%
 flops    13 x     4 x     2                36192       0.0%    100.0%      0.0%
 flops     2 x     4 x    13                36192       0.0%    100.0%      0.0%
 flops     4 x     4 x    13                48672       0.0%    100.0%      0.0%
 flops     4 x     4 x     4                48896      31.7%     68.3%      0.0%
 flops    13 x    13 x     4                55432       0.0%    100.0%      0.0%
 flops    13 x     4 x     4                64896       0.0%    100.0%      0.0%
 flops     2 x    13 x     2                71240       0.0%    100.0%      0.0%
 flops     2 x     2 x    13                71864       0.0%    100.0%      0.0%
 flops    13 x     2 x     2                72072       0.0%    100.0%      0.0%
 flops    13 x     4 x    13               117624       0.0%    100.0%      0.0%
 flops    13 x     2 x    13               235924       0.0%    100.0%      0.0%
 flops    13 x    13 x     2               241332       0.0%    100.0%      0.0%
 flops     2 x    13 x    13               255528       0.0%    100.0%      0.0%
 flops    13 x    13 x    13               843648       0.0%      0.5%     99.5%
 flops inhomo. stacks                           0       0.0%      0.0%      0.0%
 flops total                         2.288552E+06       0.7%     62.7%     36.7%
 flops max/rank                      1.788400E+06       0.9%     52.2%     46.9%
 matmuls inhomo. stacks                         0       0.0%      0.0%      0.0%
 matmuls total                               6923       1.7%     95.5%      2.8%
 number of processed stacks                  2990       4.0%     89.6%      6.4%
 average stack size                                     1.0       2.5       1.0
 marketing flops                     2.616848E+06
```

**Comment by alazzaro** [comment]
Are we sure that the GPU is used? I mean, do you see any GPU function output in the runtime breakdown?

**Comment by oschuett** [comment]
Yes, routines like `pw_cuda_r3dc1d_3d` and `acc_transpose_blocks` show up in the timings. Now with the K20X parameters the DBCSR stats look also better:
From `RI_RPA_H2O_minimax.inp.out`:
```
-------------------------------------------------------------------------------
 -                                                                             -
 -                                DBCSR STATISTICS                             -
 -                                                                             -
 -------------------------------------------------------------------------------
 COUNTER                                    TOTAL       BLAS       SMM       ACC
 flops    13 x     5 x     4                 7280       0.0%      0.0%    100.0%
 flops     5 x    13 x     4                 7280       0.0%      0.0%    100.0%
 flops     5 x     5 x     4                 8400       0.0%      0.0%    100.0%
 flops    13 x    13 x     4                18928       0.0%      0.0%    100.0%
 flops     5 x     4 x     5                66400       0.0%      0.0%    100.0%
 flops    13 x     4 x     5                86320       0.0%      0.0%    100.0%
 flops     5 x     4 x    13                86320       0.0%      0.0%    100.0%
 flops    13 x     4 x    13               112216       0.0%      0.0%    100.0%
 flops     4 x    19 x     5               126160       0.0%    100.0%      0.0%
 flops     4 x    19 x    13               164008       0.0%    100.0%      0.0%
 flops inhomo. stacks                           0       0.0%      0.0%      0.0%
 flops total                       683.312000E+03       0.0%     42.5%     57.5%
 flops max/rank                    350.784000E+03       0.0%     41.9%     58.1%
 matmuls inhomo. stacks                         0       0.0%      0.0%      0.0%
 matmuls total                               1080       0.0%     23.1%     76.9%
 number of processed stacks                   554       0.0%     30.0%     70.0%
 average stack size                                     0.0       1.5       2.1
 marketing flops                   700.672000E+03
```

**Comment by oschuett** [comment]
Also: 
```Sun Jul  7 20:00:29 2019
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 418.67       Driver Version: 418.67       CUDA Version: 10.1     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Tesla K80           Off  | 00000000:00:04.0 Off |                    0 |
| N/A   36C    P0    57W / 149W |    884MiB / 11441MiB |     16%      Default |
+-------------------------------+----------------------+----------------------+
|   1  Tesla K80           Off  | 00000000:00:05.0 Off |                    0 |
| N/A   38C    P0    69W / 149W |    657MiB / 11441MiB |     11%      Default |
+-------------------------------+----------------------+----------------------+
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|    0   1075761      C   ...psmp/../../..//exe/local_cuda/cp2k.psmp   190MiB |
|    0   1075762      C   ...psmp/../../..//exe/local_cuda/cp2k.psmp    56MiB |
|    0   1076579      C   ...psmp/../../..//exe/local_cuda/cp2k.psmp   209MiB |
|    0   1076580      C   ...psmp/../../..//exe/local_cuda/cp2k.psmp    56MiB |
|    0   1077342      C   ...psmp/../../..//exe/local_cuda/cp2k.psmp   130MiB |
|    0   1077343      C   ...psmp/../../..//exe/local_cuda/cp2k.psmp    56MiB |
|    0   1077433      C   ...psmp/../../..//exe/local_cuda/cp2k.psmp   112MiB |
|    0   1077434      C   ...psmp/../../..//exe/local_cuda/cp2k.psmp    56MiB |
|    1   1075762      C   ...psmp/../../..//exe/local_cuda/cp2k.psmp   190MiB |
|    1   1076580      C   ...psmp/../../..//exe/local_cuda/cp2k.psmp   209MiB |
|    1   1077343      C   ...psmp/../../..//exe/local_cuda/cp2k.psmp   130MiB |
|    1   1077434      C   ...psmp/../../..//exe/local_cuda/cp2k.psmp   112MiB |
+-----------------------------------------------------------------------------+
```

**Comment by alazzaro** [comment]
No idea then. @shoshijak ?

**Comment by shoshijak** [comment]
Concerning libcusmm, JIT and the parameters found through machine learning: 
- The kernels that can be JIT-ed by libcusmm on the fly are the ones written down in the `parameters_GPU.json` of the `GPU` version for which DBCSR was compiled. No prediction of optimal parameters is done on the fly. Rather they are predicted "offline" through the procedure described in `dbcsr/src/acc/libsmm_acc/libcusmm/predict.md`, and written to the corresponding `parameters_GPU.json` file. 
- So far, I've done the machine learning procedure only for the P100 (this is why `parameters_P100.json` has many more lines than the other parameter files). Predicted parameter sets for the V100 are coming up, I just want to polish a few things before I contribute them to the repo. 
- Hence the only kernels that will be JIT-ed and run by libcusmm for the K80 are the ones in `parameters_K80.json` (only 18 kernels). I do not have any autotuning data for the K80 nor access to any K80s, so I cannot fill this gap, unfortunately. 

@oschuett, what you obtain in `H2O-ls-rtp.inp.out` is as expected: the only kernel that is in `parameters_K80.json` is the 13x13x13, which runs on "ACC". 

There are many more autotuned kernels for the K20X (3142, in fact) than for the K80, which is why you get more kernels running on GPU when using this parameter file.

**Comment by oschuett** [comment]
With two K80 GPUs the `libcp2k_unittest` and a number of farming tests crash with `CUDA RT1 Error: invalid resource handle`. My guess is that there is some confusion about the active GPU between SIRIUS and CP2K. I opened https://github.com/cp2k/dbcsr/issues/205 to track this issue.

**Comment by oschuett** [comment]
I switch to using a single Pascal P4 GPU and 24 vCPUs. Now the test pass, but for some reason they are still very slow, taking 53 minutes to finish. For comparison the [psmp](https://dashboard.cp2k.org/archive/current-psmp/index.html) test finishes within 19 minutes on 32 vCPUs.

**Comment by oschuett** [comment]
I believe, I figured out why the regtests with cuda are about 2x slower: It's the JITing of the DBCSR kernels. My measurements show that compiling a single libcusmm kernel takes about 0.2 seconds.
This compilation happens in serial and has to be repeated for each regtest. Without cuda many of our regtests actually take less than a second. Hence, the compilation overhead starts to show.

On Daint we don't see this because we traditionally use farming due to the srun overhead. The problem with farming are less useful error messages. Hence, I think the longer run times are the smaller evil. In the long run we should think about a way to get nice error messages from farming.

Btw: CUDA actually has a [build cache](https://devblogs.nvidia.com/cuda-pro-tip-understand-fat-binaries-jit-caching/), but it doesn't seem to be used for NVRTC.

**Comment by alazzaro** [comment]
This is a great investigation and it shows the reason why we really need more CUDA testing...

**Pull request merged**
