### PR TITLE
Implement Python bindings via c_int_low using f2py

### PR DESCRIPTION
**Pull request by dev-zero**

### CODE REVIEW

**Comment by vondele** [comment]
I've added the fix segfault part to svn. I don't know what to do with the python bits, I would much prefer use the iso_c_binding approach as this is a standard, and one dependency less.

**Comment by dev-zero** [comment]
It's a completely optional dependency requiring only NumPy, which you most likely will have already if you are doing any serious science using Python.

The advantage of using f2py is that you automatically get NumPy compatibility wrt arrays and a native Python extension.

I've tested the bindings using mpi4py as well already.

Am 22. April 2016 16:01:53 MESZ, schrieb Joost VandeVondele <notifications@github.com>:
>I've added the fix segfault part to svn. I don't know what to do with
>the python bits, I would much prefer use the iso_c_binding approach as
>this is a standard, and one dependency less.
>
>---
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/cp2k/cp2k/pull/2#issuecomment-213440574

-- 
Tiziano Müller
University of Zurich
Department of Chemistry
Winterthurerstrasse 190
CH-8057 Zürich

Tel: +41 44 63 54234
www.chem.uzh.ch
tiziano.mueller@chem.uzh.ch

**Comment by vondele** [comment]
I meant rather that we must maintain one more dependency on the CP2K side, while with iso_c_binding we could have an interface useful from c, c++, python, and essentially any other language. The CP2K library would also be callable from those languages independently of the used Fortran compiler. Also, it is not obvious to me what the python annotations actually mean, for example for Fortran, adding an intent to a type actually might influence code generation or signature of a function, so integer:: ierr and integer, intent(out) :: ierr are not (necessarily) the same.

**Comment by dev-zero** [comment]
Wrt the f2py annotations: Since the Fortran calling convention is by-reference there is essentially no difference for the function signature. But, since most arguments are usually `intent(in)` when unspecified, f2py assumes them to be `intent(in)` to not clutter the Python interface. So you will get

```py
cp_run_input(input_file_path,output_file_path, ierr)
```

rather than

```py
input_file_path,output_file_path, ierr = cp_run_input(input_file_path,output_file_path, ierr)
```

This works because it is save to ignore the returned value of variables (dummy arguments), but it is not save to assume that every argument is actually only a return value.

To tell f2py that a variable is actually an `intent(out)` or really an `intent(inout)` you have to write it explicitly. This does not make it assume a different signature.

So, with the `f2py intent(out)` you then get the desired:

```py
ierr = cp_run_input(input_file_path,output_file_path)
```

Internally it still generates `int ierr = 0`, but removes it from the list of function arguments on the Python side.

You can find the documentation for this here: http://docs.scipy.org/doc/numpy-dev/f2py/python-usage.html

I've rewritten the patch to use the `c_int_low.F` instead as requested.

**Comment by dev-zero** [comment]
The main problem I see at the moment with the interfaces is that we will nevertheless have to maintain two interfaces: one to use CP2K from Fortran and one to use CP2K from C/Python/all-the-rest:

If we want to provide proper C-Bindings (and not just some functions which accidentally have a C function signature), we have to do conversion of strings (length-limited vs. `\0` limited, already done in `c_int_low.F`), arrays (row- vs. column-major order) and possibly some more (callbacks for example). Meaning that when someone wants to use those functions from Fortran he will have to assume the functions to be native C-functions and convert all the calling parameters to C-style arguments, respectively convert returned strings, array, etc. back to native Fortran types.

**Comment by dev-zero** [comment]
Closing for now to investigate alternatives like Cython and CFFI.
Since we need to wrap the f2py generated code again anyway, we may want to code the wrapper in Python itself.

**Pull request closed without merging**
