### PR TITLE
Fix a few CMake issues

### PR DESCRIPTION
**Pull request by haampie**
Edit: still a few things have to be fixed to make `find_package(cp2k)` work well.

### CODE REVIEW

**Comment by haampie** [comment]
Gentle ping @mtaillefumier. Do you know what those double `@@` are about? Is that a typo or a cmake feature?

**Comment by mtaillefumier** [comment]
You can also open PR to my local repo so I keep track of the authorship without triggering the CI/CD

**Comment by mtaillefumier** [comment]
@haampie or i do the reverse. As you wish

**Comment by mtaillefumier** [comment]
[haampie](https://github.com/haampie) I opened a PR on your branch.

**Pull request closed without merging**
