### PR TITLE
Hip profiling

### PR DESCRIPTION
**Pull request by gsitaram**

### CODE REVIEW

**Comment by oschuett** [comment]
I'm very sorry, but I can not merge your PR.

Profiling is only a small part of the larger effort to add complete HIP support to CP2K. It will require coordinated changes to our flags, build system, toolchain, CI, and existing Cuda code. I'll start laying the groundwork after the upcoming 8.2 release.

So again, I'm sorry for blocking your PR. Please bear with me.

**Comment by gsitaram** [comment]
Hi @oschuett, could this PR be reopened and merged now? It will help with HIP optimization efforts.

**Comment by oschuett** [comment]
Please take a look at #1586. It moves the Cuda profiling code into the [offload](https://github.com/cp2k/cp2k/tree/master/src/offload) package and adds HIP support along the way.

**Comment by gsitaram** [comment]
> Please take a look at #1586. It moves the Cuda profiling code into the [offload](https://github.com/cp2k/cp2k/tree/master/src/offload) package and adds HIP support along the way.

Okay, changes you propose in #1586 seem even better, I'll move to that PR for more comments regarding the changes there.

**Pull request closed without merging**
