### PR TITLE
Bump COSMA to version 2.6.1

### LINKED ISSUE #2207: Failing regtests with COSMA on GPU
Since the update to COSMA 2.6, there are some regtests failing on the GPU builds. This is currently being investigated. See eth-cscs/COSMA#115 for further reference.

### PR DESCRIPTION
**Pull request by fstein93**
Fixes memory reallocation issues of the COSMA library on GPU.

Fixes #2207

### CODE REVIEW

**Comment by fstein93** [comment]
Fixes #2207

**Comment by kabicm** [comment]
Regarding the wrong result test: do we know how wrong it is? Is it a new test?

**Comment by kabicm** [comment]
Since few commits before we were passing the tests (https://github.com/cp2k/cp2k/pull/2215), I can revert few latest commits?

**Comment by oschuett** [comment]
I've seen `C-levelshift.inp` pop up before - it's a somewhat unstable test. I think this PR can be merged.

**Pull request merged**
