### PR TITLE
update GW and GW+BSE howto

### PR DESCRIPTION
**Pull request by JWilhelm**

### CODE REVIEW

**Comment by JWilhelm** [comment]
@oschuett I tried to incorporate the touch ups you made previously to the docs

**Comment by JWilhelm** [comment]
@oschuett thanks for triggering the manual generation. I cannot see yet where the issue is... Is it this? 

/opt/cp2k/docs/methods/properties/bandstructure_gw.md:226: WARNING: 'myst' cross-reference target not found: 'CP2K_INPUT.FORCE_EVAL.DFT.PROPERTIES.BANDSTRUCTURE.GW.NUM_TIME_FREQ_POINTS' [myst.xref_missing]
/opt/cp2k/docs/methods/properties/bandstructure_gw.md:230: WARNING: 'myst' cross-reference target not found: 'CP2K_INPUT.FORCE_EVAL.DFT.PROPERTIES.BANDSTRUCTURE.GW.MEMORY_PER_PROC' [myst.xref_missing]
/opt/cp2k/docs/methods/properties/bandstructure_gw.md:233: WARNING: 'myst' cross-reference target not found: 'CP2K_INPUT.FORCE_EVAL.DFT.PROPERTIES.BANDSTRUCTURE.GW.EPS_FILTER' [myst.xref_missing]
/opt/cp2k/docs/methods/properties/bandstructure_gw.md:235: WARNING: 'myst' cross-reference target not found: 'CP2K_INPUT.FORCE_EVAL.DFT.PROPERTIES.BANDSTRUCTURE.GW.REGULARIZATION_RI' [myst.xref_missing]
/opt/cp2k/docs/methods/properties/bandstructure_gw.md:239: WARNING: 'myst' cross-reference target not found: 'CP2K_INPUT.FORCE_EVAL.DFT.PROPERTIES.BANDSTRUCTURE.GW.CUTOFF_RADIUS_RI' [myst.xref_missing]
/opt/cp2k/docs/methods/properties/bandstructure_gw.md:242: WARNING: 'myst' cross-reference target not found: 'CP2K_INPUT.FORCE_EVAL.DFT.PROPERTIES.BANDSTRUCTURE.SOC' [myst.xref_missing]
/opt/cp2k/docs/methods/properties/bandstructure_gw.md:245: WARNING: 'myst' cross-reference target not found: 'CP2K_INPUT.FORCE_EVAL.DFT.PROPERTIES.BANDSTRUCTURE.BANDSTRUCTURE_PATH' [myst.xref_missing]

**Comment by oschuett** [comment]
>  I cannot see yet where the issue is... Is it this?

Yes, it should be `CP2K_INPUT.FORCE_EVAL.PROPERTIES...` - so without `DFT`.

**Comment by JWilhelm** [comment]
Thanks, Ole.

**Pull request merged**
