### PR TITLE
Docker: Upgrade CMake test to Ubuntu 24.04

### PR DESCRIPTION
**Pull request by oschuett**

### CODE REVIEW

**Comment by oschuett** [comment]
It seems the newer CMake version [has trouble](https://storage.googleapis.com/cp2k-ci/run-cp2k-cmake-adf1fd55_report.txt) to find the Pika package:

```
CMake Error (dev) at /opt/spack/var/spack/environments/myenv/spack-env/view/lib/cmake/pika/pika_setup_boost.cmake:35 (find_package):
  Policy CMP0144 is not set: find_package uses upper-case <PACKAGENAME>_ROOT
  variables.  Run "cmake --help-policy CMP0144" for policy details.  Use the
  cmake_policy command to set the policy and suppress this warning.
```

@RMeli what do you think?

**Comment by RMeli** [comment]
I think this is technically just a developer warning (triggered by a new CMake policy), turned into an error by the use of 
https://github.com/cp2k/cp2k/blob/41b088e6f0a81c464025a22d9d9e66fb1cb93ad8/tools/docker/scripts/test_regtest_cmake.sh#L27

[CMP0144](https://cmake.org/cmake/help/latest/policy/CMP0144.html) is new with CMake `3.27`. Can we silence this warning until it's fixed upstream?

**Comment by oschuett** [comment]
Is there a way for us to silence it? We're already dealing with CMP0144 here:
https://github.com/cp2k/cp2k/blob/41b088e6f0a81c464025a22d9d9e66fb1cb93ad8/CMakeLists.txt#L32

**Comment by RMeli** [comment]
> Is there a way for us to silence it?

I had a quick look, and did not find an easy way to silence this specific warning. I think we need to disable `-Werror=dev` for the time being.

I can try to fix this issue before the next `pika` release (which should happen soon), when I'm back from holidays next week.

**Comment by oschuett** [comment]
> I can try to fix this issue before the next pika release (which should happen soon)

Ok, let's just let it rest until then. Enjoy your holiday!

**Comment by RMeli** [comment]
It appears that this warning has already been fixed in `pika@0.24` (https://github.com/pika-org/pika/pull/1077). Can you please update the Spack tag as well, so that it includes the latest release?

I tested `develop-2024-05-05` locally and it works.

---

```diff
diff --git a/tools/docker/Dockerfile.test_cmake b/tools/docker/Dockerfile.test_cmake
index 730cccb80..c14dd96ba 100644
--- a/tools/docker/Dockerfile.test_cmake
+++ b/tools/docker/Dockerfile.test_cmake
@@ -3,7 +3,7 @@
 # Usage: docker build -f ./Dockerfile.test_cmake ../../
 #
 
-FROM ubuntu:22.04
+FROM ubuntu:24.04
 
 # Install common dependencies as pre-built Ubuntu packages.
 RUN apt-get update -qq && apt-get install -qq --no-install-recommends \
@@ -44,7 +44,7 @@ RUN apt-get update -qq && apt-get install -qq --no-install-recommends \
 WORKDIR /opt/spack
 RUN git init --quiet && \
     git remote add origin https://github.com/spack/spack.git && \
-    git fetch --quiet --depth 1 origin tag develop-2024-03-24 --no-tags && \
+    git fetch --quiet --depth 1 origin tag develop-2024-05-05 --no-tags && \
     git checkout --quiet FETCH_HEAD
 ENV PATH="/opt/spack/bin:${PATH}"
 
diff --git a/tools/docker/generate_dockerfiles.py b/tools/docker/generate_dockerfiles.py
index 843ad48be..62f9c67ea 100755
--- a/tools/docker/generate_dockerfiles.py
+++ b/tools/docker/generate_dockerfiles.py
@@ -746,7 +746,7 @@ RUN ./scripts/generate_arch_files.sh && rm -rf ./build
 # ======================================================================================
 def spack_env_toolchain() -> str:
     return rf"""
-FROM ubuntu:22.04
+FROM ubuntu:24.04
 
 # Install common dependencies as pre-built Ubuntu packages.
 RUN apt-get update -qq && apt-get install -qq --no-install-recommends \
@@ -787,7 +787,7 @@ RUN apt-get update -qq && apt-get install -qq --no-install-recommends \
 WORKDIR /opt/spack
 RUN git init --quiet && \
     git remote add origin https://github.com/spack/spack.git && \
-    git fetch --quiet --depth 1 origin tag develop-2024-03-24 --no-tags && \
+    git fetch --quiet --depth 1 origin tag develop-2024-05-05 --no-tags && \
     git checkout --quiet FETCH_HEAD
 ENV PATH="/opt/spack/bin:${{PATH}}"
```

**Pull request merged**
