### PR TITLE
Update sirius version and sirius input files parameters

### PR DESCRIPTION
**Pull request by mtaillefumier**
- SIRIUS is updated to the latest version : it fix some input parameters issues that were reported to us.
- Adjust the regtests because SIRIUS uses a different stopping convention during the SCF loop (the old one is still present and can be activated)

### CODE REVIEW

**Comment by dev-zero** [comment]
@mtaillefumier the changes in energies seem significant, is this expected?

**Comment by mtaillefumier** [comment]
I think I found the cause. The Xc functionals are not given to SIRIUS. I must have screwed up something.

**Comment by dev-zero** [comment]
Awesome, thanks a lot!

**Comment by oschuett** [comment]
Since this PR our [manual generation](https://dashboard.cp2k.org/archive/manual/index.html) fails occasionally.

Looking at [this example](https://storage.googleapis.com/cp2k-ci/run-cp2k-manual-af66cfe8_artifacts.txt) the invalid chars are on line 402701 of the `cp2k_input.xml` file in [this tarball](https://storage.googleapis.com/cp2k-ci/run-cp2k-manual-af66cfe8_artifacts.tgz):
```
    <KEYWORD repeats="no" removed="no">
     <NAME type="default">NUM_BANDS_TO_PRINT</NAME>
     <DATA_TYPE kind="integer">
      <N_VAR>1</N_VAR>
     </DATA_TYPE>
     <USAGE></USAGE>
     <DESCRIPTION></DESCRIPTION>
     <DEFAULT_VALUE>10</DEFAULT_VALUE>
     <LOCATION>input_cp2k_pwdft.F:187</LOCATION>
    </KEYWORD>
```

**Comment by oschuett** [comment]
@mtaillefumier, could you please take a look at the invalid chars that were introduced by this PR.

**Pull request merged**
