### PR TITLE
Kab param

### PR DESCRIPTION
**Pull request by ducryf**
The KAB_PARAM in the XTB section is ignored in the current version. The value is read in and printed to the restart file, but never used in the calculation.  This is fixed and KAB_PARAM is now correctly applied.

### CODE REVIEW

**Comment by dev-zero** [comment]
maybe I missed it, but is it possible that `xtb_control%kab_vals` and `xtb_control%kab_types` don't get deallocated?

**Comment by juerghutter** [comment]
Yes, kab_vals and kab_types have to be deallocated in cp_control_types.F in routine
xtb_control_release.

**Comment by juerghutter** [comment]
Could you also add an example input in cp2k/tests/xTB/regtest-_ ?

**Comment by ducryf** [comment]
I have added the regtest cp2k/tests/xTB/regtest-1/h2_kab.inp
and fixed the missing DEALLOCATE  inf xtb_control_release. I have also added NULLIFYs to xtb_control_create.

**Pull request merged**
