### PR TITLE
Add SPDX headers and make C banners Doxygen compatible

### LINKED ISSUE #89: Add SPDX License Headers
I think we should add [SPDX License Identifier](https://spdx.org/using-spdx-license-identifier) to our file headers. DBCSR already took [the lead](https://github.com/cp2k/dbcsr/pull/56).

### PR DESCRIPTION
**Pull request by oschuett**
Closes #89 and prepares for #1072.

### CODE REVIEW

**Comment by mkrack** [comment]
It seems that the SPDX-License-Identifier `GPL-2.0+` has been [deprecated](https://spdx.org/licenses/GPL-2.0+.html) recently and `GPL-2.0-or-later` is used instead.

**Comment by dev-zero** [comment]
you might want to check https://reuse.software/ and change the copyright line too while being at it

**Comment by oschuett** [comment]
>  SPDX-License-Identifier GPL-2.0+ has been deprecated

Upps, thanks for the hint!

> change the copyright line too while being at it

So, how would you suggest we change it?

**Comment by dev-zero** [comment]
> So, how would you suggest we change it?

    ! SPDX-FileCopyrightText: 2000-2020 CP2K developers group <https://cp2k.org>

based on the most canonical form from https://reuse.software/spec/#comment-headers

But given the option further down, even the following would be conformant:

    ! Copyright 2000-2020 CP2K developers group <https://cp2k.org>

... and I would follow their examples by adding an empty line between copyright notice and SPDX license header:

    ! SPDX-FileCopyrightText: 2000-2020 CP2K developers group <https://cp2k.org>
    !
    ! SPDX-License-Identifier: GPL-2.0-or-later

**Pull request merged**
