### PR TITLE
Switch toolchain to new Intel Fortran compiler ifx (ifort -> ifx)

### PR DESCRIPTION
**Pull request by mkrack**
This PR serves to reproduce the current problems in compiling CP2K with ifx 2024.1, namely the termination with an internal compiler error in pw_methods.F.

### CODE REVIEW

**Comment by hfp** [comment]
Thank you, Matthias!

I am working on it, the `pw_methods.F` as well as `xc.F` translation units are failing (see [here](https://github.com/hfp/xconfigure/blob/main/config/cp2k/Linux-x86-64-intelx.arch#L1109)) with both likely sharing the same cause like using array-loops inside of a workshare. This is being resolved. Beside of adjusting the compilation rules, I tried some workaround (see [here](https://github.com/hfp/cp2k/commits/master/src/pw/pw_methods.F)). However, the latter did not solve it or catch all cases.

Further, there are runtime errors as well which will be logged asap and submitted for resolution.

**Comment by mkrack** [comment]
@hfp thanks, great that you are working on this. Earlier versions of ifx succeeded to compile CP2K, but gave runtime errors. I guess recent source code changes challenged the ifx compiler again.

**Comment by hfp** [comment]
> @hfp thanks, great that you are working on this. Earlier versions of ifx succeeded to compile CP2K, but gave runtime errors. I guess recent source code changes challenged the ifx compiler again.

I remembered so too like compiled successfully, but things move quickly. In addition to CP2K's dashboard, I will have an internal test to make sure things do not break. I guess, runtime issues are somewhat feature gaps not exercised elsewhere (copying a derived type with allocatable components along perhaps intermixed with POINTER vars in the same struct or whatever). We will get it ;-)

Even the ICE with array-loops inside of a workshare is sort of a feature gap issue since when it compiled successfully, it likely did not do any worksharing...

**Comment by hfp** [comment]
( Side note [since this question came up elsewhere], IFX is not based on Flang but rather based on IFORT now "classic". I am all positive for the language itself to see investment into Fortran and to keep some viable variety with respect to compilers. )

**Pull request closed without merging**
