### PR TITLE
Named critical sections, adjusted collocate/integrate, fixed typos

### PR DESCRIPTION
**Pull request by hfp**
Named critical sections (OMP). Fixed typos one of which affects the console output (" ROT| Numer of Rotovibrational vectors:"). Minor adjustments in collocate and integrate.

### CODE REVIEW

**Comment by oschuett** [comment]
Something is really strange about this PR. The previous psmp check_run was actually OOMKilled  ¯\_(ツ)_/¯

**Comment by hfp** [comment]
I am on it and I will update the PR when it passes (I am testing this locally without further relying on CI).

**Comment by hfp** [comment]
The "wrong results" are likely because of tolerances. Variations may not only arise from code changes but also from executing on different systems in the cloud (successful/unsuccessful vectorization, different instruction set extensions / FMA, and different core counts / schedule).

**Comment by oschuett** [comment]
Dang, I thought I fixed `si7c_broy_gapw_a04_restart.inp` via 9a686185383a5cdad7bdaac201ed4b7f04b1e045 ... apparently not quite :-/
For `C4H10-qmmm-gauss-0.inp` we can adjust the tolerance.

**Comment by oschuett** [comment]
I think `si7c_broy_gapw_a04_restart.inp` actually suffers from a race condition for which I just opened #114. It only shows up in 10% of the cases. And sure enougth when I re-ran the ssmp on your PR it passed. 

We should probably still adjust the tolerance on ` C4H10-qmmm-gauss-0.inp`, but then this PR is ready to be merged.

**Comment by hfp** [comment]
Ohh, I forgot the open PR but accidentely pushed to this branch. I need to restore it.

**Pull request merged**
