### PR TITLE
Update Cray arch files

### PR DESCRIPTION
**Pull request by mkrack**
- Sync target names for ELPA with toolchain
- Adapt path names for ELPA correspondingly
- Update usage description
- Revise compiler flags

### CODE REVIEW

**Comment by oschuett** [comment]
Oh, won't disabling OpenMP severely hurt ELPA's performance?

We actually just upgraded to `MPI_THREAD_SERIALIZED` to keep it working (#1564).

**Comment by mkrack** [comment]
Right, I forgot to restrict the change in install_elpa.sh to Cray toolchain builds where OpenMP is effectively disabled already.

**Comment by oschuett** [comment]
> Cray toolchain builds where OpenMP is effectively disabled already.

I wasn't aware of that. Can you elaborate? This would still affect a large part of our user base.

**Comment by mkrack** [comment]
These [build flags](https://github.com/cp2k/cp2k/blob/5da5e8ed3126c5a52c1b70c7996a60254e540919/tools/toolchain/scripts/stage5/install_elpa.sh#L80) already allow ELPA to set the number of OMP threads to one at runtime which happens on Cray XC40/50.

**Comment by oschuett** [comment]
> These build flags already allow ELPA to set the number of OMP threads to one at runtime which happens on Cray XC40/50.

But that's pretty bad, right? Does it even make sense keep using ELPA in that case?

**Comment by mkrack** [comment]
Of course, the CPU version of ELPA without OpenMP is much faster than ScaLAPACK (56s vs 135s per SCF iteration step involving a 29k by 29k matrix diagonalization using 288 CRAY-XC50 cores). I run most of my production cases with OMP_NUM_THREADS=1 anyway unless the memory demand per MPI task does not allow this. The GPU kernel is slightly faster (10%) than the fastest CPU kernel for that case.

**Comment by oschuett** [comment]
Thanks a lot for clarifying!

Did you also observe deadlocks like #1830 and #1788?

I'm fine with disabling it for now, but we'll eventually need OpenMP support for AMD EPYC and ARM based machines.

**Comment by mkrack** [comment]
ELPA with OpenMP is only disabled for Cray systems in the moment. We can further fine-tune the flags based on the actual target system, such that ARM and AMD EPYC are not affected.

**Pull request merged**
