### PR TITLE
Darwin arch files work on Intel and ARM

### PR DESCRIPTION
**Pull request by fxcoudert**
Rename the arch files accordingly

### CODE REVIEW

**Comment by fxcoudert** [comment]
The name `Darwin-IntelMacintosh-gfortran` is actually misleading, since there is no architecture-specific content in those files. CP2K compilers perfectly fine for Apple Silicon (we ship binaries for it in Homebrew already), the new ARM macOS platform.

**Comment by dev-zero** [comment]
> The name `Darwin-IntelMacintosh-gfortran` is actually misleading, since there is no architecture-specific content in those files. CP2K compilers perfectly fine for Apple Silicon (we ship binaries for it in Homebrew already), the new ARM macOS platform.

Good to know, thanks!

**Comment by dev-zero** [comment]
Maybe call them `Darwin-macOS-gfortran.*` to make it clearer for those less involved in software development?

**Comment by fxcoudert** [comment]
`Darwin-macOS-gfortran` would be like gnu-linux (kernel and OS). So I'd rather keep `Darwin-gfortran`, or `macOS-gfortran` if you find that clearer, but not both.

**Comment by dev-zero** [comment]
well, then let's leave it as this

**Pull request merged**
