### PR TITLE
HFX warning for KS sparsity

### PR DESCRIPTION
**Pull request by BelizSertcan**
modify KS sparsity warning for HFX calculations to recommend the more efficient MIN_PAIR_LIST_RADIUS keyword.

### CODE REVIEW

**Comment by oschuett** [comment]
I'm not sure about this change. 

The [FAQ page](https://www.cp2k.org/faq:hfx_eps_warning) goes to great lengths to explain why `EPS_PGF_ORB` and `EPS_FILTER_MATRIX` are needed. Whereas it's not clear to me from the [description](https://manual.cp2k.org/trunk/CP2K_INPUT/FORCE_EVAL/DFT/QS.html#MIN_PAIR_LIST_RADIUS) what exactly setting `MIN_PAIR_LIST_RADIUS` to -1 does.

**Comment by BelizSertcan** [comment]
@oschuett I modified the message. I also added a short section to the faq page but cannot publish myself.

**Comment by abussy** [comment]
I think the new message is clearer. I also think this change is quite important, because people tend to use exceedingly small values of EPS_PGF_ORB, leading to a lot of wasted CPU time. Provided that the link in the warning is also updated, I think this is ok to go.

**Comment by BelizSertcan** [comment]
I published the new message to FAQ page.

**Comment by oschuett** [comment]
Thank for updating the FAQ page. I didn't realize `MIN_PAIR_LIST_RADIUS` was a novel keyword. Now everything makes sense :-)

**Pull request merged**
