### PR TITLE
feature/misc improvements

### PR DESCRIPTION
**Pull request by dev-zero**

### CODE REVIEW

**Comment by oschuett** [comment]
I'm curious, which "new linter" did you use to re-format the basissets and pseudos ? Can we integrate it into `make pretty`?

**Comment by dev-zero** [comment]
@oschuett mine from https://github.com/cp2k/cp2k-input-tools ... `cp2k-datafile-lint --inplace [basis|potential] [file]`

**Comment by dev-zero** [comment]
simple docs can be found here: https://cp2k-input-tools.readthedocs.io/en/latest/

**Comment by oschuett** [comment]
Thanks for the link! Are you also planing a release in the near future? The current version seems to not yet contain the `cp2k-datafile-lint` tool.

**Pull request merged**
