### PR TITLE
Enable RMA tests for any number of ranks

### PR DESCRIPTION
**Pull request by alazzaro**

### CODE REVIEW

**Comment by alazzaro** [comment]
@oschuett Triggered by the discussion at https://github.com/cp2k/cp2k/issues/2125, I'm now enabling the RMA tests for any number of ranks. It passes the MPICH, but I would like to try the OpenMPI too (historically OpenMPI is not good with RMA calls). Could you tell me why the OpenMPI stops with:
```
<<< /opt/cp2k/regtesting/TEST-local-psmp-2022-05-24_08-38-36/QS/regtest-stda-force (53 of 313) done in 57.67 sec
make[3]: *** [/opt/cp2k/Makefile:253: test] Killed
make[2]: *** [/opt/cp2k/Makefile:148: test] Error 2
make[1]: *** [/opt/cp2k/Makefile:125: psmp] Error 2
make: *** [Makefile:120: test] Error 2
Removing intermediate container 1dcfa48a7f43
```

?

**Comment by oschuett** [comment]
It probably ran out of memory or `/deb/shm`. I'll take a closer look this evening.

**Comment by oschuett** [comment]
I ran the OpenMPI test locally via:
```
cd tools/docker; docker build -f Dockerfile.test_openmpi-psmp --shm-size=1g  ../../
```
It seems the RMA tests get stuck and just gobble up memory until they timeout. In my case the container used up to 70GB while the CI's limit is 22GB and normal consumption is around 12GB. Hence, there seems to be something seriously wrong with OpenMPI's RMA implementation.

AFAIK, RMA never really caught on because of poor vendor support. So, I'm wondering if we should maybe simply drop it?

**Comment by alazzaro** [comment]
> 
> AFAIK, RMA never really caught on because of poor vendor support. So, I'm wondering if we should maybe simply drop it?

No, this is not an option. RMA algo runs quite well on Cray-mpi (MPICH based) with quite good speed-ups and in general with MPICH (and Intel MPI). OpenMPI needs to be properly compiled and requires hardware support from the network. 
What I will do is to [avoid RMA](https://github.com/cp2k/dbcsr/commit/029cf0e6a0e3b7f4e6ed335482725a658f5d83ed) in DBCSR when OpenMPI is used.

**Pull request merged**
