### PR TITLE
singles correction (RSE) to RPA

### PR DESCRIPTION
**Pull request by rybkinjr**

### CODE REVIEW

**Comment by alazzaro** [comment]
@rybkinjr 
It seems that, as a result of this PR, the tests on Swan are failing with wrong results:

QS/regtest-ri-rpa-rse/RI_RPA_RSE_H2_minus.inp.out
QS/regtest-ri-rpa-rse/Cubic_RPA_RSE_H2.inp.out 

From what I can see, my guess is that this is due OpenMP threads. Swan uses 4 threads, while all other tests use 2. I can test Swan with 2 threads, but I would appreciate if you can a local regtest with 4 threads...

**Comment by rybkinjr** [comment]
Thanks for the comment, Alfio. I will chek the OMP directives myself.

**Comment by alazzaro** [comment]
I can confirm the problem doesn't happen with 1 single thread (PSMP with a single thread). Now I'm checking SSMP with a single thread. I suggest to use the flag:
```
-fsanitize=thread
```
and check the tests with 4 threads...

**Comment by alazzaro** [comment]
Confirm, also SSMP with 1 thread runs fine. So I suggest to use SSMP compiled with `-fsanitize=thread` and check for data races in the two tests...

**Comment by alazzaro** [comment]
For the record, the problem was fixed via #535

**Pull request merged**
