### PR TITLE
Dashboard: Remove defunct testers

### PR DESCRIPTION
**Pull request by oschuett**

### CODE REVIEW

**Comment by alazzaro** [comment]
Please no. Why so? 
We have to keep Daint performance testers as legacy tests, at least to check that Daint is OK.
I would appreciate if you can leave them.
Concerning the HIP, leave it comment.

**Comment by hfp** [comment]
Also, Daint-CI for DBCSR did not ran for several weeks. Are Daint-CI tests (or any tests running on Daint) supposed to work?

**Comment by alazzaro** [comment]
> Also, Daint-CI for DBCSR did not ran for several weeks. Are Daint-CI tests (or any tests running on Daint) supposed to work?

This is completely unrelated here... Open a DBCSR issue ;)

**Comment by alazzaro** [comment]
Please, keep the CCE too. We can discover problems like: 

https://github.com/cp2k/cp2k/pull/1579#issuecomment-915921963

**Pull request merged**
