### PR TITLE
OpenBLAS 0.3.19 -> 0.3.20

### PR DESCRIPTION
**Pull request by mkrack**
- Update arch files

### CODE REVIEW

**Comment by oschuett** [comment]
After this innocent update the timing of `dbm_multiply` in the [RI-HFX_32OMP](https://dashboard.cp2k.org/archive/perf-openmp/index.html) benchmark increased by 50% from [170s to 252s](https://dashboard.cp2k.org/archive/perf-openmp/RI-HFX_H2O-32_timings_32omp.txt).

This might be due to https://github.com/xianyi/OpenBLAS/pull/2775, which is currently under debate for a rollback https://github.com/xianyi/OpenBLAS/pull/3546.

I guess, we are affected because DBM calls [dgemm](https://github.com/cp2k/cp2k/blob/master/src/dbm/dbm_multiply_cpu.c#L111) (through libxsmm) within an OpenMP parallel region.

@hfp, what do you think? Should we maybe add our 2ct to that debate?

**Comment by hfp** [comment]
@oschuett I am confused about what this patch actually achieves and the statements sounding somewhat obscure (as always when things get optimized ;-). What I captured is (not saying I confirm/agree) is that changing the OpenMP teamsize from parallel region to another can cause overhead. It seems OpenBLAS uses OpenMP parallelism by controlling the teamsize from region to region depending on problem size. That latter sounds somewhat wrong to me since OMP_DYNAMIC exist and one can set chunk sizes. Anyway, it's hard to oversee since this may also mix with numerical reproducible results under multiple threads. Obviously, if we got hit by a slowdown we can make a neutral statement and what for resolution (might be some revert). One issue is `dgemm` does not exist in a single-thread flavor wrt to API like "dgemm_sequential" but rather controls things under the hood.

I can see that OpenBLAS is quite important and perhaps there is a way to get this issue under control. I wonder why this happens, do we have OpenMP Nested turned on?

**Comment by hfp** [comment]
Maybe [this is relevant](https://github.com/cp2k/cp2k/issues/1826#issuecomment-998838763) and if so, we can attempt to disable nested parallelism programmatically.

**Comment by oschuett** [comment]
> we can attempt to disable nested parallelism programmatically.

Yes, this seems like the more robust solution.

Do you think we can just disable nested parallelism globally, ie. when cp2k starts up? Or should we be more selective and only changed the value during `dbm_multiply`?

**Comment by hfp** [comment]
I checked OpenBLAS source and it seems it's not calling `omp_set_nested` (which would make things more complicated). Regarding you question, I think disabling it globally is appropriate. If we want to handle it very nicely, we can check if any environment variable related to OpenMP nested parallelism is present and then just omitting to change things... though this is a bit intriguing...  First step is to confirm nested parallelism is indeed enabled. I always thought nesting is disabled by default...

**Comment by oschuett** [comment]
Ok, it wasn't the nesting. I also can't reproduce the slowdown on my AMD CPU. Furthermore, this [OpenBLAS release](https://github.com/xianyi/OpenBLAS/compare/v0.3.19...v0.3.20) had a number of fixes around AVX512. So my new theory is that we're suffering from [dynamic frequency scaling](https://en.wikipedia.org/wiki/Advanced_Vector_Extensions#Downclocking).

It seems only `dbm_multiply` with many threads is affected, which kinda makes sense because it still contains some serial code paths that eventually start to dominate. Hence, I will let this slowdown go and instead focus on fixing the threading issues in DBM.

**Pull request merged**
