### PR TITLE
Cleanup and a small improvements for the gpu backend

### PR DESCRIPTION
**Pull request by mtaillefumier**
- remove the hybrid cpu/gpu backend
- fix the warnings when -pedantic is on (there are still some warmings occuring when -DBDEBUG is given to the compiler)
- add output information in the global section that indicates which grid backend is used for the calculations
- small performance improvements for the integrate kernel. Reduction to shared memory for the coefficients is removed from the zyx loop for  l = 0 and l = 1.
- shift some atomic operations outside loops when possible.

### CODE REVIEW

**Comment by oschuett** [comment]
There are some [failures](https://storage.googleapis.com/cp2k-ci/run-cp2k-cuda-pascal-42b067e2_report.txt) in the cuda test. Since I'm currently preparing a very similar change to trade registers for atomics, I'd prefer if you could just remove [that commit](https://github.com/cp2k/cp2k/pull/1421/commits/91801f644676b1fdd8eb5e33db3d5283e780bbeb) from this PR.

Also, please remove these [unnecessary tabs](https://github.com/cp2k/cp2k/pull/1421/files#diff-46247d60cddb3c18498cc5247e360c2c467294191cbb7387ec71dc928a358334R14-R32).

**Comment by mtaillefumier** [comment]
faulty commit removed and tabs are corrected.

**Comment by alazzaro** [comment]
I assume that, as a result of this PR, the GPU regtests are now failing:

https://storage.googleapis.com/cp2k-ci/dashboard_cuda-pascal_report.txt

**Comment by mtaillefumier** [comment]
The two patchs add output in the global section and remove code with
signature change of a very limited number of functions. The GPU backend
is untouched.

I am running the regtests again to try to catch the error.

**Comment by mtaillefumier** [comment]
All tests are passing on K80 (I have locally).

**Comment by alazzaro** [comment]
Maybe @oschuett has a clue. The stacktrace is:

```
Backtrace for this error:
#0  0x7f79c5a84d01 in ???
#1  0x7f79c5a83ed5 in ???
#2  0x7f79b27ef20f in ???
#3  0x557bef7e5041 in grid_library_counter_add
	at /workspace/cp2k/src/grid/common/grid_library.c:109
#4  0x557bef79121a in ???
#5  0x557bef78e368 in grid_collocate_task_list
	at /workspace/cp2k/src/grid/grid_task_list.c:145
#6  0x557bef789fa0 in __grid_api_MOD_grid_collocate_task_list
	at /workspace/cp2k/src/grid/grid_api.F:1084
#7  0x557bee36261c in __qs_collocate_density_MOD_calculate_rho_elec
	at /workspace/cp2k/src/qs_collocate_density.F:1547
#8  0x557bee4fa162 in __qs_rho_methods_MOD_qs_rho_update_rho
	at /workspace/cp2k/src/qs_rho_methods.F:445
#9  0x557beedd22f9 in __qs_scf_loop_utils_MOD_qs_scf_rho_update
	at /workspace/cp2k/src/qs_scf_loop_utils.F:628
#10  0x557bee5ae8c4 in __qs_scf_MOD_scf_env_do_scf
	at /workspace/cp2k/src/qs_scf.F:537
#11  0x557bee5baf7d in __qs_scf_MOD_scf
	at /workspace/cp2k/src/qs_scf.F:232
#12  0x557bee3ddce9 in __qs_energy_MOD_qs_energies
	at /workspace/cp2k/src/qs_energy.F:88
#13  0x557beedf84a4 in qs_forces
	at /workspace/cp2k/src/qs_force.F:209
#14  0x557beedfbe9b in __qs_force_MOD_qs_calc_energy_force
	at /workspace/cp2k/src/qs_force.F:114
#15  0x557bee99fec5 in __force_env_methods_MOD_force_env_calc_energy_force
	at /workspace/cp2k/src/force_env_methods.F:271
#16  0x557beddfbc83 in cp2k_run
	at /workspace/cp2k/src/start/cp2k_runs.F:346
#17  0x557beddfefdc in __cp2k_runs_MOD_run_input
	at /workspace/cp2k/src/start/cp2k_runs.F:982
#18  0x557bedde96c9 in cp2k
	at /workspace/cp2k/src/start/cp2k.F:337
#19  0x557bedb149de in main
	at /workspace/cp2k/src/start/cp2k.F:44
```

**Comment by mtaillefumier** [comment]
Actually I may have a clue. The number of backends is directly used
every a table depends on it. The way to at fix this is to define a constant

#define GRID_NUMBER_OF_BACKENDS_ ....

It is a problem with global variables in codes.

**Comment by oschuett** [comment]
It's correct that the number of backends is hardcoded, but I don't think this is the reason because effectively we're just keeping some unused counters around. Nevertheless,  #1422 won't hurt.

Unfortunately, I also can not (yet) reproduce this problem either. I'll keep digging.

**Comment by mtaillefumier** [comment]
I keep digging as well. I really can not see what is triggering this bug.

**Pull request merged**
