### PR TITLE
Add hybrid-meta-GGA functionals from Libxc

### PR DESCRIPTION
**Pull request by fstein93**
I applied the patches from Stanislaw Simko to Libxc such that we can use hybrid meta-GGAs from Libxc plus some regtests. See https://groups.google.com/forum/#!topic/cp2k/ARya5uM-pA4

### CODE REVIEW

**Comment by fstein93** [comment]
Unfortunately, it worked on my machine. Without UKS the code is running in principle. Due to the error it might be an issue within Libxc. I will try a different functional.

**Comment by fstein93** [comment]
I really wonder about that error. I can compile libxc 4.3.4 with the above code locally (gnu 4.9.2) and on Daint (gnu 6.0.4) and the regtests run without issues.

**Comment by oschuett** [comment]
Are you running the debug version? Note that floating point exception are only trapped when you compile with ` -ffpe-trap=invalid,zero,overflow`.

**Comment by fstein93** [comment]
Unfortunately, gnu 4.9.2 does not provide this (and some other) option(s) of your pdbg. With -ffpe-trap=invalid,zero,overflow, I get the same issues with other functionals on Daint. In the above check, the same test without uks and some others use the same lines of code and it is working there. So it is probably not our code causing the numerical issues.
Because a lot of functionals in Libxc are known to show floating point errors, the error in this test might really arise from Libxc, not from my modifications.
Maybe density smoothing helps.

**Comment by fstein93** [comment]
Would it be okay for you to simply remove the failing regtest?

**Comment by oschuett** [comment]
Yeah, floating point exception in libraries can be tricky. The best solution would be of course to fix libxc because this might be an actual bug. Alternatively, you can disable trapping while calling into the library. We do this e.g. for [pexsi](https://github.com/cp2k/cp2k/blob/master/src/pexsi_interface.F#L394).

You shouldn't remove the test, unless you think libxc is actually broken. However, in that case it would be best to remove the functionality from cp2k altogether to protect our users.

**Comment by fstein93** [comment]
I think mGGA hybrids are a quite useful feature of Libxc that is requested. So I don't want to remove that code; the numerical issues of Libxc are known. If they occur, the user can make use of features of CP2K like density smoothing (examples are available even for Libxc), otherwise the Libxc developers have to be informed. (By the way, the Libxc 5.0 comes up with a new API again.)

**Comment by oschuett** [comment]
If you have confidence in the results then temporarily disabling the trapping is the way to go.

Just to clarify: In the past we have encounter a few broken functionals in libxc, which we then disabled to protect our users. Hence, I wasn't sure if this is another one of those cases.

I think, it's great that you're adding these functionals!

**Comment by fstein93** [comment]
I removed the failing regtest. But to give at least a hint to the user, I used the provided flags from Libxc to tell the user if a functional is not considered stable. (Right now (4.3.4) that holds for every functional but they plan to really use the flag later.)
I absolutely understand your position. But I think, this solutions is the best one. It will probably work for later releases, too. (Except they change the API too much)

**Comment by fstein93** [comment]
The failing regtest is not caused by me (cf. CP2K dashboard).

**Comment by fstein93** [comment]
Do you still have some concerns?

**Pull request merged**
