### PR TITLE
parsing: add options to mark keywords as deprecated/removed

### PR DESCRIPTION
**Pull request by dev-zero**

### CODE REVIEW

**Comment by dev-zero** [comment]
Hmm, why exactly wasn't that triggered before:

https://github.com/cp2k/cp2k/blob/55f6b15fd96a0fce25305a0e74b0b20b39f63b9f/src/qs_kind_types.F#L1596-L1601

**Comment by oschuett** [comment]
Because [that test](https://github.com/cp2k/cp2k/blob/master/tools/regtesting/check_inputs.py) only runs `cp2k.x --check`. This show that moving the deprecation check to the parsing stage is a really good idea :-)

**Comment by dev-zero** [comment]
> Because [that test](https://github.com/cp2k/cp2k/blob/master/tools/regtesting/check_inputs.py) only runs `cp2k.x --check`. This show that moving the deprecation check to the parsing stage is a really good idea :-)

Thanks.

**Comment by oschuett** [comment]
Btw, are you also planning to surface the deprecation notices in the [html manual](https://github.com/cp2k/cp2k/blob/master/tools/manual/cp2k_input.xsl)?

**Pull request merged**
