### PR TITLE
Add a CP2K_BUILD_OPTIONS with some default dependencies.

### PR DESCRIPTION
**Pull request by mtaillefumier**
- Add -DCP2K_BUILD_OPTIONS=DEFAULT,MINIMAL,SERIAL,FULL to avoid specifying which dependency should be included in the build. The default behavior (when the argument is not speficied) lets the user decide what to include.
- Fix the installation of the libcp2k.h header file
- Add option to compile libcp2k shared version

### CODE REVIEW

**Comment by mtaillefumier** [comment]
@oschuett @mkrack : Let me know if you wish more build options (just select the dependencies). 
NB : 

- the default is user full control. 
- cmake supports similar functionalities (Release, etc) but it is probably better to keep this separated as we allow combination minimal-debug etc...

**Comment by mkrack** [comment]
@mtaillefumier Thanks, we can always elaborate further on this later.

**Comment by mtaillefumier** [comment]
too fast. I wanted to include a minor change :/. Never mind I will open an other pr

**Comment by mkrack** [comment]
@mtaillefumier No problem, I just want to avoid having PRs hang around too long for no good reason.

**Pull request merged**
