### PR TITLE
buildsystem: introduce optional CLD and CLDFLAGS

### PR DESCRIPTION
**Pull request by dev-zero**
When using the Intel Fortran compiler to link an object file containing
a C main routine, one has to specify `-nofor_main`, see also:

  https://software.intel.com/en-us/node/525351

Introduce optional `CLD` and `CLDFLAGS` variables to be able to
set/override the linker/linker-flags when linking C-executables.

### CODE REVIEW

**Comment by dev-zero** [comment]
@agloess, @ibethune: you might want to take a look as well

**Comment by dev-zero** [comment]
solved in a different way in the meantime

**Comment by hfp** [comment]
Hmm, I am still seeing this issue when the libcp2k_unittest executable is linked i.e., -nofor_main is missed from the link line (ifort/mpiifort) despite of 0d6e9ec.

**Comment by dev-zero** [comment]
@hfp: did you specify `LDFLAGS_C = $(FCFLAGS) -nofor_main` in your arch-file (see e3dff698a151f85c8a8c46653416331aa60f6cf6)?

**Comment by hfp** [comment]
@dev-zero Thank you, I did not capture this one!

**Pull request closed without merging**
