### PR TITLE
Allow CPASSERT to be elided if NDEBUG is defined. Introduced CP_VERSIONx.

### PR DESCRIPTION
**Pull request by hfp**
Allow CPASSERT to be elided if NDEBUG is defined. Introduced CP_VERSION3 and CP_VERSION4 to consistently calculate a single (version-)number such that it can be compared using the preprocessor e.g., #if CP_VERSION3(1, 2, 3) <= CP_VERSION3(MYLIB_MAJOR, MYLIB_MINOR, MYLIB_UPDATE).

This change may allow to setup a test with NDEBUG defined aka "release build" (not meant to spawn a discussion of whether or not an actual production-build should contain assertions). Anyhow, a test with NDEBUG can unveil potential side-effects or misuses of CPASSERT. The current status (to my knowledge) is that regression tests fail to a large portion if CPASSERT is elided.

**Note**: `make pretty` appears to fail parsing this change.

### CODE REVIEW

**Comment by dev-zero** [comment]
any concrete users for the `CP_VERSION{3,4}` macros?

**Comment by hfp** [comment]
CP_VERSION3 can be used for the GNU Compiler Collection (and other codes) e.g., CP_VERSION3(__GNUC__, __GNUC_MINOR__, __GNUC_PATCHLEVEL__). This also works GNU Fortran (despite the fact that it is called "GNUC"):

```bash
gfortran -dM -E - < /dev/null > symbols.txt
grep GNUC symbols.txt
```
The CP_VERSION4 can be used for LIBXSMM (version consists of major, minor, update, and patch). I may have patches in the future that then allow to maintain compatibility with older LIBXSMM.

**Comment by hfp** [comment]
Well, CP_VERSION3 would probably suffice with LIBXSMM as well (unless one intends to conditionally take unreleased changes). I can rework to a single CPVERSION macro if that is more suitable with respect to the macro-name.

**Comment by dev-zero** [comment]
> CP_VERSION3 can be used for the GNU Compiler Collection (and other codes) e.g., CP_VERSION3(**GNUC**, **GNUC_MINOR**, **GNUC_PATCHLEVEL**). This also works GNU Fortran (despite the fact that it is called "GNUC"):
> 
> ```shell
> gfortran -dM -E - < /dev/null > symbols.txt
> grep GNUC symbols.txt
> ```
> 
> The CP_VERSION4 can be used for LIBXSMM (version consists of major, minor, update, and patch). I may have patches in the future that then allow to maintain compatibility with older LIBXSMM.

nice!

The only thing I wondered is whether it would be clearer if the range for major/minor/update is the same for both versions since there are projects which leave away the patch version number on the first release (starting with a `1.2.3` and then making a patch `1.2.3.1.` which would compare differently if I would do `CP_VERSION3(1.2.3) > CP_VERSION4(1,2,3,1)`.
Otherwise a line of documentation that one should never compare a `CP_VERSION3 to a CP_VERSION4` would be sufficient.

**Comment by hfp** [comment]
Indeed CP_ASSERT{3|4} were not compatible since the ranges were tuned to not overflow even with 32-bit integer. Anyhow, let's not worry -- I consolidated into a single CPVERSION. If there is any need ever to check four components, we can add CPASSERT4 by then.

**Comment by dev-zero** [comment]
That's fine too. I guess bit-shifts are not allowed for a preprocessor in compat mode?

**Comment by hfp** [comment]
No idea, but this code works for GNU Fortran and IFORT and the current expression is in use since years (in my fork of CP2K which was previously the "intel" branch of CP2K's Git-mirror).

**Comment by hfp** [comment]
The remaining failure with `sdbg` is related to spglib or specifically this library is missed on the link-line. Perhaps this PR may wait for other fixes (see dashboard failures).

**Pull request merged**
