### PR TITLE
Direct unconstrained variable-metric localization of one-electron orbitals

### PR DESCRIPTION
**Pull request by rzk1**

### CODE REVIEW

**Comment by dev-zero** [comment]
@rzk1 the issue is likely to be the line-length

Can you please add `INTENT` specifiers for newly added routines (for example in `almo_scf.F`)?

Otherwise LGTM.

**Comment by rzk1** [comment]
Sorry for multiple minor corrections. sdbg compiles fine on my machine with the same flags. I will go through the intent flags in the new subroutines. I ask my team to be more attentive to these details.

**Comment by rzk1** [comment]
INTENT specifiers have been added

**Comment by dev-zero** [comment]
> Sorry for multiple minor corrections. sdbg compiles fine on my machine with the same flags. I will go through the intent flags in the new subroutines. I ask my team to be more attentive to these details.

No problem at all. Thanks a lot!

**Comment by rzk1** [comment]
Hi guys. Is there anything else you would like us to do to have this PR merged?

**Comment by dev-zero** [comment]
@rzk1 no, it's ok. If it is ok for you I'll squash the commits into one on merge and get rid of the intermediate "prettify/doxify" comments.

Resulting commit message will be:

```
Direct unconstrained variable-metric localization of one-electron orbitals (#762)

* NLMO reimplemented, compiles and works for 2 test files
* NLMO refactoring to enable virtual localization in the future
* Diagonal BFGS is implemented and tested on Si. Same convergence as SD
* Adds L-BFGS: code compiles, 1st test fails
* L-BFGS minor bug resolved. Energy goes up in 1st tiny L-BFGS line search
* q: remove minus sign
* Compiled and tested refactoring NLMO objct func with virtual and compact implementation
* Modified NLMOs keyword description
* Tested code and added NLMO input file
* Fix NLMO memory leaks, enter correct reference values for NLMO tests
* Fix print bug in NLMO PCG optimizer
* Fix all valgrind errors related to uninitialized variables
* Fix unused dummy argument in almo_scf_lbfgs_types.F
```

Ok or do you want to tidy the commit message further?

**Comment by rzk1** [comment]
@dev-zero it is OK to squash. Thanks!

**Pull request merged**
