### PR TITLE
fix coding conventions (dashboard)

### PR DESCRIPTION
**Pull request by JWilhelm**

### CODE REVIEW

**Comment by JWilhelm** [comment]
@oschuett @all On the dashboard, ssmp and psmp regtests give errors at the end of CP2K runs, for example

 
 -------------------------------------------------------------------------------
  **** **** ******  **  PROGRAM ENDED AT                 2023-08-15 21:35:29.435
 ***** ** ***  *** **   PROGRAM RAN ON                              4f45854a7652
 **    ****   ******    PROGRAM RAN BY                                 <unknown>
 ***** **    ** ** **   PROGRAM PROCESS ID                                 18830
  **** **  *******  **  PROGRAM STOPPED IN /opt/cp2k/regtesting/local/ssmp/TEST-local-ssmp-2023-08-15_21-30-49/QS/regtest-scalable-gw

Program received signal SIGSEGV: Segmentation fault - invalid memory reference.

Backtrace for this error:
#0  0x7fe7adfcead0 in ???
#1  0x7fe7adfcdc35 in ???
#2  0x7fe7adb7751f in ???
#3  0x7fe7adbd67c3 in ???
#4  0x7fe7adbd7938 in ???
#5  0x7fe7adbda4d2 in ???
#6  0x557f374123f9 in __input_keyword_types_MOD_keyword_release at /opt/cp2k/src/input/input_keyword_types.F:444
#7  0x557f3740257f in __input_section_types_MOD_section_release at /opt/cp2k/src/input/input_section_types.F:245
#8  0x557f3740235e in __input_section_types_MOD_section_release at /opt/cp2k/src/input/input_section_types.F:252
#9  0x557f374023ec in __input_section_types_MOD_section_release at /opt/cp2k/src/input/input_section_types.F:252
#10  0x557f37402394 in __input_section_types_MOD_section_release at /opt/cp2k/src/input/input_section_types.F:252
#11  0x557f374023be in __input_section_types_MOD_section_release at /opt/cp2k/src/input/input_section_types.F:252
#12  0x557f349ed28d in cp2k at /opt/cp2k/src/start/cp2k.F:382
#13  0x557f349ebb5e in main at /opt/cp2k/src/start/cp2k.F:44




By chance, do you know a way to identify what the problem is?

**Comment by oschuett** [comment]
I'll take a look.

**Comment by oschuett** [comment]
It's a double free of `gw_env%nkp_grid_chi_eps_W_input`.

The pointer is set here to an array that belongs to the input system:
https://github.com/cp2k/cp2k/blob/5080151e8b1ac516ab82332683adfb2cbf2d479f/src/gw_utils.F#L183

...and then deallocated by the GW code:
https://github.com/cp2k/cp2k/blob/5080151e8b1ac516ab82332683adfb2cbf2d479f/src/gw_types.F#L200

**Comment by JWilhelm** [comment]
Thanks a lot for figuring this out, Ole!

**Comment by JWilhelm** [comment]
Let's hope that all bugs are fixed now...

**Pull request merged**
