### PR TITLE
Add -march compiler flag for CPUID recognition

### PR DESCRIPTION
**Pull request by mkrack**

### CODE REVIEW

**Comment by oschuett** [comment]
I'm surprised #3560 is causing you trouble because it was meant to be backwards compatible:
https://github.com/cp2k/cp2k/blob/4a68796e230453a1bef558615a994c3f1ad1b491/tests/do_regtest.py#L259-L260

**Comment by oschuett** [comment]
> I'm surprised https://github.com/cp2k/cp2k/pull/3560 is causing you trouble because it was meant to be backwards compatible:


Oh, I now realized my mistake. I'll submit a fix later.

**Comment by mkrack** [comment]
@oschuett A general fix is appreciated. Currently `--mpiexec 'mpiexec -n {N}'` has to be specified for `TESTOPTS` to get an alternative `mpiexec` command working.

**Comment by mkrack** [comment]
> > I'm surprised #3560 is causing you trouble because it was meant to be backwards compatible:
> 
> Oh, I now realized my mistake. I'll submit a fix later.

If your fix allows to revert the fix in this PR for the Intel docker file, please do so.

**Comment by oschuett** [comment]
> If your fix allows to revert the fix in this PR for the Intel docker file, please do so.

I just merged #3574. It should now work without your change to the Intel docker file.

**Comment by oschuett** [comment]
Seems like my fix worked. Sorry for the hassle.

Btw, this PR would be a good candidate for [Squash and merge](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/incorporating-changes-from-a-pull-request/merging-a-pull-request#merging-a-pull-request).

**Pull request merged**
