### PR TITLE
Add CMake support for cuSOLVERMp

### PR DESCRIPTION
**Pull request by jpoto**
@oschuett Can you check it?

### CODE REVIEW

**Comment by hfp** [comment]
Perhaps put a description when the PR leaves the Draft state (click [...] -> [Edit] for the PR's top box).

**Comment by sliwowitz** [comment]
This works for me. I'm on Fedora with Nvidia HPC SDK. I need to provide a path to the Nvidia HPC SDK libraries, so with the latest 24.9 version, I use: `-DCMAKE_PREFIX_PATH="/opt/nvidia/hpc_sdk/Linux_x86_64/24.9/compilers/bin;/opt/nvidia/hpc_sdk/Linux_x86_64/24.9/math_libs;/opt/nvidia/hpc_sdk/Linux_x86_64/24.9/comm_libs/12.6/hpcx/latest/ucc;/opt/nvidia/hpc_sdk/Linux_x86_64/24.9/comm_libs/12.6/hpcx/latest/ucx" -DCP2K_USE_ACCEL="CUDA" -DCP2K_USE_CUSOLVER_MP=ON`

(Though this is not specifically related to this pull request, on Fedora 40 I also need a custom gcc and gfortran as nvcc is not compatible with gcc 14, I specify those as environment variables `CUDAHOSTCC=/opt/gcc-13/bin/gcc-13.3 CUDAHOSTCXX=/opt/gcc-13/bin/g++-13.3 FC=/opt/gcc-13/bin/gfortran-13.3`)

**Comment by oschuett** [comment]
I haven't used cuSOLVERMp in a while. @RMeli what do you think?

**Comment by RMeli** [comment]
@oschuett Unfortunately we were not able to run cuSolverMp on our newest system yet, therefore I never tried to use it with CP2K and I don't have any useful input at this time.

**Pull request merged**
