### PR TITLE
Sort various things for build reproducibility

### PR DESCRIPTION
**Pull request by keszybz**

### CODE REVIEW

**Comment by LecrisUT** [comment]
Thanks @keszybz. Shouldn't the order be determined by cmake though when it processes the Fortran files afterwards?

(seems you need to run the `/packit build` command, can you add a comment with that?)

**Comment by keszybz** [comment]
> Shouldn't the order be determined by cmake though when it processes the Fortran files afterwards?

I don't think cmake is involved in processing this in any way. The first patch is about generated Fortran code which would then be used as-is. (The code is included in the -debugsources subpackage, but it's also hashed into the buildid of compiled code, so the difference in sources causes a cascading set of small differences.)  The second patch is about code which runs during build and does some checks (IIUC), and the patch just makes this output more stable.

**Comment by keszybz** [comment]
```
/builddir/build/BUILD/cp2k-0.0.0-build/cp2k-0.0.0/src/transport_env_types.F:153:59:

  153 |          CALL dbcsr_csr_destroy(transport_env%imagp_matrix)
      |                                                           1
Error: â€˜imagp_matrixâ€™ at (1) is not a member of the â€˜transport_env_typeâ€™ structure
```
I don't think this is caused by my changes.

(FWIW, I built the package locally for rawhide and the build was successful.)

**Comment by LecrisUT** [comment]
Ah ok, kinda makes sense. What did you use to detect this?

I'll try to fix the packit builds soon, I think it's just related to the version of `dbcsr`, I''ll test it out with a copr build

**Comment by keszybz** [comment]
> Ah ok, kinda makes sense. What did you use to detect this?

I'm doing test rebuilds using my own tooling: https://github.com/keszybz/fedora-repro-build.
The initiative now has  a home page and a matrix channel: https://docs.fedoraproject.org/en-US/reproducible-builds/.

**Comment by LecrisUT** [comment]
Seems to be indeed an issue with `dbcsr` version. Will fix it in https://github.com/cp2k/cp2k/pull/3743, and try to get dbcsr update backported to the other branches also: https://src.fedoraproject.org/rpms/dbcsr/pull-request/2

**Comment by LecrisUT** [comment]
@keszybz can you rebase and re-run packit CI. The fedora builders should be fine now

**Comment by keszybz** [comment]
I got a mail from the dashboard that something failed, but it seems to be timing issue? No idea really.

**Comment by LecrisUT** [comment]
:shrug: probably numerical error
```
>>> /opt/cp2k/build/bin/TEST-ssmp-2024-11-19_07-27-01/QS/regtest-gpw-8
    si8_broy_wc_crazy_ene.inp                                                              168.8408091 WRONG RESULT (   1.40 sec)
```

**Comment by oschuett** [comment]
Don't worry. Unfortunately, we get false alarms quite regularly. We try to balance the numeric noise with the execution time of the tests.

**Pull request merged**
