### PR TITLE
Refactor MPI handles

### PR DESCRIPTION
**Pull request by fstein93**
This PR encapsulates all MPI handles used outside of the MPI wrapper module, i.e. communicators, requests, files, windows (the last one is not used in CP2K). File handles are only encapsulated as far as they are connected to the MPI module, otherwise, the ordinary Fortran integer handle will be used as in most parts of the code, the output is written to the regular output file. the status handles are not encapsulated as they are never used outside of the wrapper.

This PR prepares the introduction of the MPI-Fortran-2008 module.

I am open for comments.

### CODE REVIEW

**Comment by oschuett** [comment]
Awesome!
Referencing #1030 for posterity.

**Comment by fstein93** [comment]
Now, the handles are stored in separate module-private variables. Then, we define the CP2K wrappers and use the handles of the null objects as defaults for our handles and finally, we can define the CP2K-wrapped MPI constants.

**Comment by oschuett** [comment]
Looks very good!

I was wondering what is your plan for switching over to the MPI-Fortran-2008 module? Will there be a flag or do we need to make a hard cut over? In the later case we should probably wait until after the release.

**Comment by fstein93** [comment]
I think we should wait for the next release to include the Fortran-2008 module but we can already merge this PR before the next release as it just provides a plain refactoring without any differences in the actual content/performance.

**Comment by alazzaro** [comment]
Checking the code, I found a number of mpi2 and mpi3 mentions still present in the code:

https://github.com/cp2k/cp2k/search?q=mpi2
https://github.com/cp2k/cp2k/search?q=mpi3

**Pull request merged**
