### PR TITLE
Docker: Disable core dumps and handle preemption gracefully

### PR DESCRIPTION
**Pull request by oschuett**

### CODE REVIEW

**Comment by dev-zero** [comment]
Please don't. This changes default behavior on a system without the possibility to get the default behavior back.

**Comment by oschuett** [comment]
Ok, how about a `max_coredump_size` argument that defaults to zero?

It came up this morning with #256. Every regtest failed, keeping the machine busy with writing core dumps until the kubernetes job eventually timed out before it could print the stack traces.

**Comment by dev-zero** [comment]
yes, but use `$(ulimit -c)` as the default, then set the argument for the CI.

For systems with systemd you can easily load a coredump with gdb using

    coredumpctl gdb

**Comment by oschuett** [comment]
Maybe the better solution would be to add `ulimit -c 0` to [ci_entrypoint.sh](https://github.com/cp2k/cp2k/blob/master/tools/docker/scripts/ci_entrypoint.sh) ?

**Pull request merged**
