### PR TITLE
Docker: Add test for ARM64

### PR DESCRIPTION
**Pull request by oschuett**

### CODE REVIEW

**Review by hfp — COMMENTED** [review]
It would be nice to start testing LIBXSMM on AArch64 at some point. We have not released LIBXSMM 2.0, but support as needed by CP2K is ready since quite some time. Though, it requires to rely on our main branch. To decouple from our daily development, I recommend for instance `6f883620f58afdeebab28039fc9cf580e76a5ec6`.

**Comment by oschuett** [comment]
Thanks for the info @hfp! Do you have a ETA for libxsmm 2.0? We still have a number of other issues to work out, e.g. #1855. So, perhaps the simplest solution is to just wait for the official release?

**Comment by mkrack** [comment]
Thanks @oschuett. It is great that we have now an ARM64 tester which can reproduce the issues with the test inputs  in `QS/regtest-gw-kpoints` faster detected by [this tester](https://dashboard.cp2k.org/archive/gnu-aarch64-psmp/index.html) for quite a while already. I will retire that slow regression tester.

**Comment by hfp** [comment]
> Thanks for the info @hfp! Do you have a ETA for libxsmm 2.0? We still have a number of other issues to work out, e.g. #1855. So, perhaps the simplest solution is to just wait for the official release?

We plan 2.0 for next year. Though, it slipped since we ever said "2.0" (1+ years). This is because of our research goals are somewhat different from just delivering predictable release cycles. Anyway, our cleanup work made good progress and I can see doing a release next year regardless of some pending items (if not closed over the year's end). Functionality (or even correctness) as of current releases (CP2K, DBM, DBCSR, etc.) is not expected to be related to any remaining 2.0 goals (libxsmm), hence one can just take for instance the earlier mentioned SHA.

**Comment by hfp** [comment]
LIBXSMM's internal dependencies changed and using the Fortran interface now requires to link `xsmm`, `xsmmext`, and `xsmmf` (this order). I hope to get back to the previous dependencies (not "ext"), but even if previous deps are back, linking all of them should not harm.

**Comment by oschuett** [comment]
Thanks for the link order @hfp. Unfortunately, I'm getting segfaults, e.g. when running `dbt_unittest`. So, I'll leave libxsmm out of this PR.

**Comment by oschuett** [comment]
> It is great that we have now an ARM64 tester which can reproduce the issues with the test inputs in QS/regtest-gw-kpoints

Yes, it's good that the problem is so well reproducible.

> detected by [this tester](https://dashboard.cp2k.org/archive/gnu-aarch64-psmp/index.html) for quite a while already.

Indeed! Thanks for doing all the hard ground work. I was very impressed when the toolchain simply worked on ARM.

> I will retire that slow regression tester.

Go ahead. The new tester is up and running. For now ARM instances are still somewhat scarce on GCP (max 16 core per region), but this will certainly improve. Then we can also start to monitor performance.

**Pull request merged**
