### PR TITLE
docker: intel oneapi and gnu based build

### PR DESCRIPTION
**Pull request by hfp**
* Docker image based on "rockylinux" (RPM distro) to supply something "HPC" (not necessarily HPE/Cray/Suse).
* Recipe aka HFP's "best" (minus obscure bits); effectively: GNU Fortran + Intel MPI + Intel MKL + LIBXSMM.
* Non-reproducible (as every image) because of pulling bits from the Internet (dependencies).
* Of interest: LIBINT/latest/2.9.0 bootstrap for CP2K.

### CODE REVIEW

**Comment by hfp** [comment]
An OCI compliant image which is not necessarily tested with native Docker (I used sudo/podman). It should work with Docker out-of-the-box because of requiring less features (only OCI compliance).

**Comment by hfp** [comment]
This is LIBINT/latest/2.9.0 bootstrapped for CP2K.
**Current LIBINT in CP2K**: 2.6.0

**Review by mkrack — COMMENTED** [review]
All Dockerfiles are created by the generation script [generate_dockerfiles.py](https://github.com/mkrack/cp2k/blob/master/tools/docker/generate_dockerfiles.py). Therefore, this Dockerfile is special in this respect.

**Comment by hfp** [comment]
> All Dockerfiles are created by the generation script [generate_dockerfiles.py](https://github.com/mkrack/cp2k/blob/master/tools/docker/generate_dockerfiles.py). Therefore, this Dockerfile is special in this respect.

Yes, that's true. Also, it deviates the way it pulls dependencies etc. Certainly it builds CP2K in a way not supported by the toolchain like GNU Compiler, Intel MPI, and Intel MKL. I am not insisting in taking the PR; I am actually not sure if should go in.

I can put the Dockerfile elsewhere (if I wanted to document the way I am building CP2K). Perhaps it's also useful if we want a recipe for generating CP2K's flavor of LIBINT.

**Comment by oschuett** [comment]
Since this is a Dockerfile for running CP2K in production, it should go into the [cp2k-containers](https://github.com/cp2k/cp2k-containers)  repo.

For testing Intel's HPC Kit we use [Dockerfile.test_intel-psmp](https://github.com/cp2k/cp2k/blob/master/tools/docker/Dockerfile.test_intel-psmp)  - although it's broken (again) because of a missing gpg key.


> Perhaps it's also useful if we want a recipe for generating CP2K's flavor of LIBINT.

That is definitely super useful! With our current setup the best place for the info is probably the [libint-cp2k](https://github.com/cp2k/libint-cp2k) repo.

**Comment by hfp** [comment]
PR will be retargeted to [cp2k-containers](https://github.com/cp2k/cp2k-containers) repository.

> although it's broken (again) because of a missing gpg key.

I had something like this too on my own system (Debian) and I needed to re-add the oneAPI repository according to the current documentation (perhaps just a new key).

**Pull request closed without merging**
