### PR TITLE
hotfix for sirius

### PR DESCRIPTION
**Pull request by mtaillefumier**
- series of hotfix for sirius including U+V, etc...

Signed-off-by: Dr. Mathieu Taillefumier <mathieu.taillefumier@free.fr>

### CODE REVIEW

**Comment by mtaillefumier** [comment]
could someone fix this https://www.cp2k.org/static/downloads/SIRIUS-7.4.0.tar.gz

**Comment by mkrack** [comment]
> could someone fix this https://www.cp2k.org/static/downloads/SIRIUS-7.4.0.tar.gz

Fixed.

**Comment by mtaillefumier** [comment]
thanks a lot

**Comment by mkrack** [comment]
@mtaillefumier Some testers (e.g. [pdbg](https://storage.googleapis.com/cp2k-ci/dashboard_pdbg_report.txt), [ARM64](https://storage.googleapis.com/cp2k-ci/dashboard_arm64-psmp_report.txt)) show problems with the new SIRIUS release.

**Pull request merged**
