### PR TITLE
[WIP] Remove Arnoldi and dbcsr_vector to DBCSR

### PR DESCRIPTION
**Pull request by dithillobothrium**
The pull request changes module names in 'uses' and removes arnoldi, dbcsrx, iterate_matrix.F files/directories.

### CODE REVIEW

**Comment by dithillobothrium** [comment]
one needs to change target branch

**Comment by dithillobothrium** [comment]
It was temporarily because it was not clear what to do with these functions. I need to move them in dbcsr.

**Comment by oschuett** [comment]
I think you'll have to duplicate `abnormal_value()` because it is also used in other places within CP2K.
Maybe you could do that first before merging this PR?

Alternatively, `iterate_matrix.F` could also remain within CP2K for the time being. In my opinion it is rather high-level and hence it is anyways questionable if DBCSR is the right place.

**Comment by dithillobothrium** [comment]
why is it conflicting now?

**Comment by alazzaro** [comment]
I think because Ole touched the files you are removing (changed the year), so now git gets confused...

**Comment by dithillobothrium** [comment]
Now it is fine

**Comment by dithillobothrium** [comment]
We need to cancel this PR, I have now new PR about inclusion of Linear Algebra to CP2K

**Comment by dev-zero** [comment]
@dithillobothrium you can always force push to your remote branch `la_to_dbcsr` to update this PR, but ok

**Comment by dithillobothrium** [comment]
Oh, I thought this is another branch...

**Comment by dithillobothrium** [comment]
I can specify my branch for DBCSR submodule but it should not be committed. How to set this properly?

**Comment by oschuett** [comment]
Is this still being worked on?

**Comment by dithillobothrium** [comment]
Its pending. My branch was ready to merge but it should be done together DBCSR and CP2K. It depends on those who decide what to include in which release. Now the branch more far from the master and should be every time updated, but I don't do that.

**Pull request closed without merging**
