### PR TITLE
Offload: support OpenCL

### PR DESCRIPTION
**Pull request by hfp**
* This work "short-cuts" supporting OpenCL by leveraging DBCSR's OpenCL backend to implement CP2K's Offload interface.
  - Future work (may be soon) can decide/settle where the actual glue code is hosted ("OpenCL backend").
  - OpenCL is very close to CUDA (streams/queues, events, etc), however, an OpenCL BE accounts for differences.
  - Pointer arithmetic on the host using device pointers is not supported with OpenCL (without additional effort), e.g.,
    DBM is implemented by relying on device pointer arithmetic.
  - OpenCL abstracts device memory with an opaque "cl_mem" structure (does not expose actual device pointers).
* Some functions on CP2K's Offload interface (once derived from DBCSR's ACC interface) remain "TODO", i.e.,
  for the time being offload_runtime.h "disables" support for Grid and PW/FFTs
  - Defines for __NO_OFFLOAD_GRID and __NO_OFFLOAD_PW must be still given for the Fortran code.
* Some changes remove CUDA and HIP specific code-paths by relying on Offload runtime (e.g., offload_create_buffer).
* Some changes also address problematic code format (multi-line control-flow w/o curly braces/block, etc).
* Further updating INSTALL.md and white-listing/removing certain items are part of follow-up changes.

### CODE REVIEW

**Comment by hfp** [comment]
Test `QS/regtest-tddfpt-force-2/h2o_f13.inp` with [CUDA Pascal Regtest](https://storage.googleapis.com/cp2k-ci/run-cp2k-cuda-pascal-571f34bd_report.txt) is flagged wrong. However, this is apparently unrelated to this PR. CUDA Pascal Regtest was mainly triggered to check successful compilation.

**Comment by oschuett** [comment]
This is very exciting!

Should we setup a dashboard test for it?

> DBM is implemented by relying on device pointer arithmetic.

This should be straightforward to change.

**Comment by hfp** [comment]
Thanks! There are more PRs to come, at least one covering the actual DBM changes/kernel. I mean this perfectly works on NVidia too, so it should be simple to finally setup a Dashboard entry.

**Comment by hfp** [comment]
Also, I have to work on providing a clean/minimal ARCH file and support in our CMake infra ;-)

**Comment by hfp** [comment]
To share a little sneak peek (@JWilhelm), I ran `benchmarks/QS_low_scaling_GW/GW.inp` on systems with four Intel GPUs which looks like:

> job                                 nn     nr       nt       tts
--
 cp2k-gwls-192481        1       16      7       340.494
cp2k-gwls-192547        2       32      3       162.532
cp2k-gwls-192549        4       16      7       105.373
cp2k-gwls-192483        16      16      7       56.934

The columns denote the job title, number of nodes, number of ranks per node, number of threads (no smt), and total time to solution (in seconds). My DBM-kernel so far is not optimized at this point, e.g., does not even use shared/local memory.

**Pull request merged**
