### PR TITLE
Gal19

### PR DESCRIPTION
**Pull request by pclabaut**
Hello,
Here is the implementation of the novel forcefield GAL19, described by https://pubs.acs.org/doi/10.1021/acs.jctc.0c00091 to evaluate noble metal/water interactions.
The implementation is working and I hope that you will find it suitable for your code.
Best regards,

Clabaut Paul

[acs.jctc.0c00091(1).pdf](https://github.com/cp2k/cp2k/files/4797372/acs.jctc.0c00091.1.pdf)

### CODE REVIEW

**Review by pseewald — CHANGES_REQUESTED** [review]
you accidentally changed the DBCSR submodule (`exts/dbcsr`). Can you revert this? Let me know if you need help doing this.

**Comment by pclabaut** [comment]
Hello, thanks for the answer,
I figured It could be that but then I tried to download the ext/dbscr directory from the cp2k main page again but git doesn't detect any difference with the one one of my branch.

**Comment by pseewald** [comment]
I added a commit to reset the submodule

**Comment by pclabaut** [comment]
Oh, I see, thanks !
Did you detect any change then ?
I'm really surprised that git status coulnd't see any

**Comment by pclabaut** [comment]
Apparently, it failed again in compiling the dbcsr part.
Any idea ?

**Comment by pseewald** [comment]
> Oh, I see, thanks !
> Did you detect any change then ?
> I'm really surprised that git status coulnd't see any

You changed the commit of DBCSR submodule (see `git show 9687c635a2ee9094caf10d49e918a8b95fa026f1 exts`). This should be fixed now.

**Comment by pclabaut** [comment]
But the testing fails again.
Your commit did apply to the gal19 branch, right?
So there is still a problem in the dbscr part of the branch after you reseted it ?

**Comment by pseewald** [comment]
This is a wild guess: there seem to be a non-ascii character in this pull request leading to a failure in our `makedep.py` python script.

**Comment by pclabaut** [comment]
It would be consistent with the error message. But how come it fails in this branch and not in the master of cp2k ?

**Comment by pseewald** [comment]
> It would be consistent with the error message. But how come it fails in this branch and not in the master of cp2k ?

because you added the character (in CP2K, not DBCSR). I fixed it and hope that now tests run through.

**Review by pseewald — APPROVED** [review]

**Comment by pclabaut** [comment]
Oh, I see, so the non-ascii character was in my files but detected by a python script from the ext/dbcsr part. 
Thank you a lot for spotting that!

**Comment by pseewald** [comment]
> Oh, I see, so the non-ascii character was in my files but detected by a python script from the ext/dbcsr part.
> Thank you a lot for spotting that!

No this had nothing to do with DBCSR, the python script is in CP2K.

the tests report 2 leaks that should be fixed.

**Comment by pclabaut** [comment]
Yes, I'm currently loocking into that. Thanks again!

**Comment by pclabaut** [comment]
Hello again, 
The leak is fixed and the tests have passed. What is the next step?
Thanks again for the help !

**Pull request merged**
