### PR TITLE
Adjust tolerance.

### PR DESCRIPTION
**Pull request by oschuett**

### CODE REVIEW

**Comment by dev-zero** [comment]
Can you please add a comment on which arch/platform/compiler the current tolerance failed?

**Comment by oschuett** [comment]
The `h2o_ot_precond_7.inp` failed here:
https://dashboard.cp2k.org/archive/current-ssmp/commit_3fbbec4104122a0d4063128c6620913ae359cc4f.txt.
The other two failed on Swan, but I can't find it back. It probably disappeared. I'll remove it for the time beeing.

**Comment by alazzaro** [comment]
Yeap, on Swan it was a small glitch... By re-executing the job the problem disappeared... Anyway, the new tolerances are more stable...

**Comment by oschuett** [comment]
Well if you only re-executed then the glitch will likely reappear. So, I'm putting those back in.

**Comment by alazzaro** [comment]
> Well if you only re-executed then the glitch will likely reappear. So, I'm putting those back in.

Indeed, that's what I meant with "new tolerances are more stable".

**Comment by dev-zero** [comment]
@oschuett what I meant: add the comment inside the commit message such that people who do a `git log` get a bit more information other than the obvious "adjusted tolerance"

**Pull request merged**
