### PR TITLE
offload+grid: Change license to BSD-3-Clause

### PR DESCRIPTION
**Pull request by oschuett**
We're switching to a permissive license for our newly written GPU code to make it easier for vendors to contribute. 

The vast majority of CP2K's code base will of course remain under the GPL, which we should not and cannot change.

Besides myself, the following people contributed to the new grid code: @mtaillefumier, @hfp, @mkrack, @dev-zero, @ltalirz. Could each of you please state that you agree to this license change.

### CODE REVIEW

**Comment by hfp** [comment]
Fine with me. Please go ahead and change the license to BSD-3-Clause for offload+grid code.

**Comment by mtaillefumier** [comment]
Same for me. Fine with this change

**Comment by ltalirz** [comment]
Sure!

**Comment by mkrack** [comment]
No objections.

**Comment by dev-zero** [comment]
ACK.

**Pull request merged**
