### PR TITLE
Added Mulliken and Hirshfeld charges to the results framework

### PR DESCRIPTION
**Pull request by Pibemanden**
As mentioned in #2130 I have added the` [MULLIKEN-CHARGES]` and `[HIRSHFELD-CHARGES]` to the fortran/C++ interface for CP2K.

### CODE REVIEW

**Comment by oschuett** [comment]
Thanks for contributing!

Could you please once run `make pretty` to fix the formatting. Furthermore, you could extend [libcp2k_unittest.c](https://github.com/cp2k/cp2k/blob/master/src/start/libcp2k_unittest.c) to cover your use case - if you like.

**Comment by Pibemanden** [comment]
I tried running `make pretty` but it didn't change anything in the files I have altered. It only detected some errors in files which I haven't touched, but not changes there either according to git. So I am wondering what is causing the errors being reported by your build system.

**Comment by oschuett** [comment]
> So I am wondering what is causing the errors being reported by your build system.

Can you share what kind of errors it reports? Generally, we test quite rigorously that everything is prettified. One thing you could try is updating your git submodules: ```git submodule update --recursive```.

**Comment by Pibemanden** [comment]
Sorry I forgot to clone with the recursive tag before running `make pretty`, seems like everything might be working now though.

**Comment by oschuett** [comment]
Yeah, these sub-modules are annoying. Hopefully, we can ditch them someday. Glad it worked out after all.

**Pull request merged**
