### PR TITLE
grid: Add GPU backend

### PR DESCRIPTION
**Pull request by oschuett**

### CODE REVIEW

**Comment by alazzaro** [comment]
Something wrong due to this PR for the Daint regtest:

https://www.cp2k.org/static/regtest/trunk/cscs-daint-xc50_gpu/CRAY_XC50-gfortran_gpu.psmp.out

Any clue?

**Comment by oschuett** [comment]
I introduced the new flag `-D__GRID_CUDA`. Please try `make distclean`.

**Comment by alazzaro** [comment]
It does `make distclean` for before each multiplication. Is this macro mandatory? I mean, can we avoid it and still compiling with CUDA?

**Comment by oschuett** [comment]
> I mean, can we avoid it and still compiling with CUDA?

Probably no. ... I guess that's a bug.

**Comment by alazzaro** [comment]
Well, the next question is: is there any reason to switch it off when CUDA is enabled? Can we have only the CUDA macro?

**Comment by oschuett** [comment]
> is there any reason to switch it off when CUDA is enabled? 

Since this is brand new code, it's probably good to have a way to disable it.

Furthermore, we do not yet have a Cuda flag. We have `__PW_CUDA` and some more for DBCSR. Nevertheless, it might a good idea to introduce a single flag to enable all Cuda kernels in CP2K at some point.

**Comment by alazzaro** [comment]
Wait, the -D_ACC is still there for CP2K in general (it is not used in DBCSR):

`-D__ACC` needed to enable accelerator support`

**Comment by mtaillefumier** [comment]
I agree that we need to be able to disable it if needed, especially with
two different ways to do computation on GPU.

**Comment by alazzaro** [comment]
Disabling is fine, but I would rather go to a switch a runtime...

**Comment by mtaillefumier** [comment]
There is a switch at runtime.

section GRID, keyword BACKEND.

if you add this

section GRID

BACKEND REF

&end

in the global section of your input file you have what you want.

**Comment by oschuett** [comment]
The `__ACC` flag is not used in CP2K either - apparently it was left behind during the DBCSR extraction.

I think, 2021 will be the year where we figure out how to manage multiple Cuda kernels running on multiple GPUs.
However, for the time being I'd rather keep separate kill switches for maximum control.

I've opened #1172 to fix your build issues.

**Comment by alazzaro** [comment]
We are going in a loop here... I don't need to disable it... I'm asking if there is a need to avoid the compilation if CUDA is enabled in CP2K (via -D_ACC). You said you want to keep the macro (a specific macro for it) for some development reason, and now you are telling me that there is a flag at compile time, so I wonder what we happen if I have disabled at compile time and then I enabled at runtime...

**Comment by mtaillefumier** [comment]
You have two options. Either you compile cp2k the -D__GRID_CUDA (it is a
compilation constant not a macro, collocate will run on GPU by default)
and you can run cp2k normally with an extra option in your input file
*or* you can compile cp2k all together *without* the -D__GRID_CUDA
compilation flags (collocate is done on cpu). It is up to you. The
current PR just fix the compilation issue nothing more.

**Comment by oschuett** [comment]
> I wonder what we happen if I have disabled at compile time and then I enabled at runtime...

Then you'll end up [here](https://github.com/cp2k/cp2k/blob/master/src/grid/grid_task_list.c#L72) :-)

> You said you want to keep the macro 

Actually, I think we should remove `-D__ACC` for the time being because it's too generic.

> I'm asking if there is a need to avoid the compilation if CUDA is enabled in 

While there is a runtime flag, the compile time flag is more thorough.

**Comment by alazzaro** [comment]
> The `__ACC` flag is not used in CP2K either - apparently it was left behind during the DBCSR extraction.
> 
> I think, 2021 will be the year where we figure out how to manage multiple Cuda kernels running on multiple GPUs.
> However, for the time being I'd rather keep separate kill switches for maximum control.

Well, it is a placeholder for future activity ;)

https://github.com/cp2k/cp2k/blob/8bb4190b3113b082ab19807aa877e0f86d433aeb/src/cp2k_info.F#L134-L136

**Comment by mtaillefumier** [comment]
it might but I agree with @oschuett <https://github.com/oschuett>.
-D__ACC is way too generic. We need a different flag for this core part
of cp2k.

**Comment by oschuett** [comment]
> Well, it is a placeholder for future activity ;)

Yes, once we have gathered some experience I'm happy to reconsider. However, for the next release (in about 6 weeks) I'd very much like to keep a separate flags so people have to opt in explicitly.

**Pull request merged**
