### PR TITLE
Update fprettify git submodule

### PR DESCRIPTION
**Pull request by mabraham**
The fprettify project has been moved, which breaks the git clone behavior

### CODE REVIEW

**Comment by mabraham** [comment]
Context: GROMACS project would like to build CI containers containing a pre-built CP2K for it to link against, starting from v9.1 when the support was formally offered by CP2K. But a recursive git clone fails to check out fprettify because the project has moved. Updating the submodule definition in your repo might be useful for more people than GROMACS.

**Comment by mabraham** [comment]
Thanks!

**Comment by mkrack** [comment]
@mabraham It seems that the fix does not work because of a typo: `fortan`

**Comment by mabraham** [comment]
Sorry! https://github.com/cp2k/cp2k/pull/3657

**Comment by oschuett** [comment]
I've updated the url also in all later support branches.

**Pull request merged**
