### PR TITLE
Docker: Re-enable keepalive mode for GPU regtest

### PR DESCRIPTION
**Pull request by oschuett**
This got accidentally lost in #1917.

### CODE REVIEW

**Comment by hfp** [comment]
This is waiting for https://github.com/cp2k/dbcsr/pull/601 to appear as RC1?

**Comment by oschuett** [comment]
> This is waiting for https://github.com/cp2k/dbcsr/pull/601 to appear as RC1?

Yes.

**Comment by hfp** [comment]
After the next RC of DBCSR (or final release), it can be considered testing the OpenCL backend using, e.g., Dashboard's "Performance CUDA Volta". I have [prepared](https://github.com/cp2k/cp2k/blob/master/INSTALL.md#2u-opencl-devices) Toolchain and Dockerfiles to allow blending of CUDA and OpenCL (the latter only affects DBCSR). A prerequisite for MPI and multiple ranks targeting the same device/card is to bring card(s) into default mode rather than "exclusive process" (`nvidia-smi`).

**Comment by alazzaro** [comment]
@hfp next DBCSR RC is expected tomorrow ;)

**Comment by hfp** [comment]
> @hfp next DBCSR RC is expected tomorrow ;)

Thank you, Alfio! Will this already include avoiding the C-matrix readbacks/reductions for certain cases?

**Comment by alazzaro** [comment]
> > @hfp next DBCSR RC is expected tomorrow ;)
> 
> Thank you, Alfio! Will this already include avoiding the C-matrix readbacks/reductions for certain cases?

No, that is part of a new RC with optimizations improvements, which will need more careful checking at scale. Current version (2.3.0-rc1) should fix all issues. I'm merging here.

**Pull request merged**
