### PR TITLE
Various fixes for the cmake build system

### PR DESCRIPTION
**Pull request by mtaillefumier**
- SPLA offloading could not be turned on because I used the wrong variable name
- added missing plumed dependency

### CODE REVIEW

**Comment by oschuett** [comment]
There seems to be a merge conflict.

**Comment by mtaillefumier** [comment]
the RPA gradients commit is showing up for no apparent reasons. It is not even in my git history.

**Comment by mtaillefumier** [comment]
should be fine now.

**Comment by oschuett** [comment]
> the RPA gradients commit is showing up for no apparent reasons. It is not even in my git history.

I looks to me like you rebased the upstream branch onto your own instead of the other way around. This is why in your branch the latest upstream commits appear after your own commit.

**Pull request merged**
