### PR TITLE
RI basis sets for MOLOPT basis sets for whole periodic table (might be discussed in developer meeting)

### PR DESCRIPTION
**Pull request by JWilhelm**
For RI-MP2, RI-RPA, GW

### CODE REVIEW

**Comment by JWilhelm** [comment]
it seems that there were no comments on the developer's meeting concerning the RI basis sets... for users this might be helpful, because for many RI-RPA and GW methods, the automatic RI basis set generation won't work because the automatic RI basis set generator generates contracted RI basis sets which at present cannot be handled by RI-RPA and GW (if I'm not wrong)

**Comment by juerghutter** [comment]
A possible solution (or a fall back) could be provided by
create_primitive_basis_set in aobasis/basis_set_types.F

**Comment by JWilhelm** [comment]
> A possible solution (or a fall back) could be provided by create_primitive_basis_set in aobasis/basis_set_types.F

Thanks, Jürg. We will check at a later stage. It is great to potentially get uncontracted RI basis by that routine.

**Comment by oschuett** [comment]
So, shall I merge this PR?

**Comment by JWilhelm** [comment]
> So, shall I merge this PR?

From my side that will be great!

**Pull request merged**
