### PR TITLE
Dashboard: Drop GCC 4.8

### PR DESCRIPTION
**Pull request by oschuett**

### CODE REVIEW

**Comment by alazzaro** [comment]
Just to confirm, are we dropping 4.8.x everywhere?
If so, then I will update https://www.cp2k.org/dev:compiler_support

**Comment by oschuett** [comment]
Well, I don't seem much reason for keeping it. Right now we can't run with libint2, which takes out many important features. And once #356 is merged it won't compile at all.

**Comment by dev-zero** [comment]
I guess 4.9 will also be out once we're using `SOURCE=` or `MOLD=`, maybe target 5.4 which was afaik at some point widely used in Linux distros?

**Comment by alazzaro** [comment]
OK, 4.8.x is out now, I'm still keeping 4.9.x (used at UZH).

https://www.cp2k.org/dev:compiler_support

**Pull request merged**
