### PR TITLE
Fix restart rtp vg

### PR DESCRIPTION
**Pull request by glb96**
Create a new input to define an initial value for the vector potential for RTP calculations in the velocity gauge approach.
This input key is also used to restart an RTP calculation.

### CODE REVIEW

**Comment by glb96** [comment]
Hey @fstein93 
Here is the modified version of the code to move the new object into an allocatable. However, when I compile I have  this error: 

/users/glebreton/Software/cp2k/src/cp_control_utils.F:2174:9:

          efield%vec_pot_initial = tmp_vals
         1
Error: Code for reallocating the allocatable array at (1) will be added [-Werror=realloc-lhs]

This is strange because I defined one line before the size of  efield%vec_pot_initial to be the one of tmp_vals. 
May you (or anyone) help me?

**Comment by fstein93** [comment]
Modify it to `efield%vec_pot_initial(:) = tmp_vals`. Without providing any boundaries (including implicit one), the standard requires a reallocation of the array according to the size of the arrays on the r.h.s. whereas with the (implicit) boundaries, no reallocation will occur and the sizes of the copied (sub)arrays will be checked.

**Comment by fstein93** [comment]
Why do you open a second pull request for the same feature? If you just want to update the remote branch, use `git push --force` to enforce this update. The CI will restart automatically without the need to open another PR or open/closing the old ones.

**Comment by glb96** [comment]
In the meantime I found that: 

ALLOCATE (efield%vec_pot_initial, source=TRANSFER(tmp_vals, efield%vec_pot_initial))

also work. 
Is it better / equivalent / worst than: 

ALLOCATE (efield%vec_pot_initial(SIZE(tmp_vals))
efield%vec_pot_initial(:) = tmp_vals 

To be honest I am a bit lost about how to use the github properly. Though that opening a draft like this you be easier to discuss than working on the PR directly

**Comment by glb96** [comment]
Sorry for the new PR request. I will work on the same for future PR. 

The new object is now defined to be an allocatable instead of a pointer as requested.

**Pull request merged**
