### PR TITLE
LIBXSMM 1.15

### PR DESCRIPTION
**Pull request by hfp**

### CODE REVIEW

**Comment by hfp** [comment]
Expected to fail since https://www.cp2k.org/static/downloads/libxsmm-1.15.tar.gz is missing.

**Comment by mkrack** [comment]
libxsmm-1.15.tar.gz is now available

**Comment by mkrack** [comment]
Use f7716aa3684441646affb567a67a2975de05db2aec55714808b0f14e16a2c2a7

**Comment by hfp** [comment]
Sorry, I need to ask you to download/upload it again. I did some release update in between.

**Comment by mkrack** [comment]
@hfp Try again

**Comment by hfp** [comment]
There went something wrong with the re-test:

```
========== Fetching Git Commit ==========
fatal: Could not parse object '486e8a74a279662fdd56214d439c8b7ebe87106d'.
```

I will change something and force-push to try the normal flow.

**Pull request merged**
