### PR TITLE
Docs: Adopt Physical Review's citation style

### PR DESCRIPTION
**Pull request by oschuett**

### CODE REVIEW

**Comment by oschuett** [comment]
@JWilhelm, is [this](https://ci.cp2k.org/artifacts/run-cp2k-manual-cdfb35eb/manual/bibliography.html) what you had in mind? I wasn't quite sure how to format the issue field.

**Comment by JWilhelm** [comment]
> @JWilhelm, is [this](https://ci.cp2k.org/artifacts/run-cp2k-manual-cdfb35eb/manual/bibliography.html) what you had in mind? I wasn't quite sure how to format the issue field.

In Phys. Rev. style (which is identical to J. Chem. Phys. style), one does not report the issue. In my personal taste, I would not display the issue, because identifying an article based on an issue might be less relevant at present (giving an issue might have been advantageous when searching a physical library)

**Comment by oschuett** [comment]
> I would not display the issue,

Ok, I've removed the issue from `generate_input_reference.py`.

If nobody objects then I'll remove it entirely from `bibliography.F` with a later PR.

**Comment by mkrack** [comment]
> > @JWilhelm, is [this](https://ci.cp2k.org/artifacts/run-cp2k-manual-cdfb35eb/manual/bibliography.html) what you had in mind? I wasn't quite sure how to format the issue field.
> 
> In Phys. Rev. style (which is identical to J. Chem. Phys. style), one does not report the issue. In my personal taste, I would not display the issue, because identifying an article based on an issue might be less relevant at present (giving an issue might have been advantageous when searching a physical library)

If we want to be compliant with a certain bib style, JabRef returns the following format templates (BibTeX BST files) for the
- American Physical Society: [1] B. Smith, B. Jones, and J. Williams, _Title of the Test Entry_, BibTeX Journal **34**, 45 (2016).
- Americal Chemical Society: (1) Smith, B.; Jones, B.; Williams, J. Title of the Test Entry. _BibTeX Journal_ **2016**, 34 (3), 45–67. https://doi.org/10.1001/bla.blubb.

I think we have still some kind of mixture. Personally, I prefer the APS citation style.

**Comment by oschuett** [comment]
> Personally, I prefer the APS citation style.

I don't want to be the tie-breaker. Are there any other opinions?

**Comment by JWilhelm** [comment]
> > Personally, I prefer the APS citation style.
> 
> I don't want to be the tie-breaker. Are there any other opinions?

APS style = Phys. Rev. style, so it appears to me that it is 3 (Hans, Matthias, me) for APS style, 0 for ACS style, if I didn't miss something?

**Comment by oschuett** [comment]
Ok, I believe after [this change](https://github.com/cp2k/cp2k/compare/e26c1d2c4465b6687aad3c71fbf753a604be7efd..922d74858170e83fef7912a3bbc97bd6540458ab) it now matches the APS style.

**Pull request merged**
