### PR TITLE
Retire older Intel testers

### PR DESCRIPTION
**Pull request by mkrack**

### CODE REVIEW

**Comment by alazzaro** [comment]
Out of curiosity, not related to this PR (sorry for that), is there an explanation why the https://dashboard.cp2k.org/archive/psi-gnu-mpich-psmp/index.html is always failing?

**Comment by mkrack** [comment]
No clue, there are always the same one or two tests running into the time limit of 400s when the regression test runs as a slurm batch job. The problem does not occur when I run the same test interactively on the login node.

**Comment by alazzaro** [comment]
> No clue, there are always the same one or two tests running into the time limit of 400s when the regression test runs as a slurm batch job. The problem does not occur when I run the same test interactively on the login node.

Indeed, `QS/regtest-kp-2/cc2.inp` is always failing since this https://github.com/cp2k/cp2k/commit/452b3252e6f2376ff1818a3a99c9ccc117ee600e. But then I noticed the following in the output of the [dashboard](https://dashboard.cp2k.org/archive/psi-gnu-mpich-psmp/commit_452b3252e6f2376ff1818a3a99c9ccc117ee600e.txt):

```
# leak related to mpi or scalapack  triggers sometimes for regtest-kp-2/cc2.inp
leak:Cblacs_gridmap
leak:blacs_gridmap_
```
So maybe it is something related to leaks?

Update: Forget my previous comment, the output was always there...

**Comment by mkrack** [comment]
The test `QS/regtest-kp-2/cc2.inp` fails with TIMEOUT already much longer, i.e. at least since 400 commits ([78096bc](https://github.com/cp2k/cp2k/commit/78096bc50ec3c41c1825630b7cc5ec9938bfc15f)) whereas [452b325](https://github.com/cp2k/cp2k/commit/452b3252e6f2376ff1818a3a99c9ccc117ee600e) is "only" 135 commits ago.

**Comment by alazzaro** [comment]
Oh, I see, so it seems related to the switch to GCC 12.2 then...

**Comment by mkrack** [comment]
Yes, that's most likely the reason. There has also been an [issue](https://github.com/cp2k/cp2k/issues/2117) with OpenBLAS and GCC 12 which did not occur with GCC 11.3. Therefore, I still recommend to use rather GCC 11.3 instead of GCC 12.2 to create CP2K production binaries.

**Comment by mkrack** [comment]
@alazzaro The problem seems to appear because of the leak sanitizer. I have now disabled the leak detection with GCC 12.2 for testing.

**Pull request merged**
