### PR TITLE
Toolchain: use MKL's ScaLAPACK and FFTW when available

### PR DESCRIPTION
**Pull request by hfp**
* Moved install_fftw.sh from stage2 to stage3 (after MKL).
* Disable using separate FFTW library if MKL is linked.
* Fixed picking MKL's ScaLAPACK in case of Intel MPI.
* Show message about default MPI-kind (MPICH).
* Rely on MPICXX=mpicxx (Intel MPI).
* Adjusted MKL help line message.

### CODE REVIEW

**Comment by hfp** [comment]
The Docker based build seems to rely on an incorrect path somehow (cached?).

```text
sha256sum: /opt/cp2k-toolchain/scripts/stage2/install_fftw.sh: No such file or directory
```

Indeed, `install_fftw.sh` was moved from stage2 to stage3.

**Comment by oschuett** [comment]
Unfortunately, the install scripts have their path hard-coded within themselves: https://github.com/cp2k/cp2k/blob/master/tools/toolchain/scripts/stage2/install_fftw.sh#L61

**Comment by hfp** [comment]
> 
> 
> Unfortunately, the install scripts have their path hard-coded within themselves: https://github.com/cp2k/cp2k/blob/master/tools/toolchain/scripts/stage2/install_fftw.sh#L61

I have overlooked this, thank you very much!

**Comment by hfp** [comment]
> 
> 
> I've triggered the Cuda P4 test because it uses [Dockerfile.cuda_mkl](https://github.com/cp2k/cp2k/blob/master/tools/toolchain/Dockerfile.cuda_mkl), which is currently the only place were the CI tests MKL.
> 
> Since Intel has now made all their software available via OneAPI, I'm contemplating to create a dedicated Dockefile for Intel.

I second the idea, Intel made repositories available for all libraries (even prior to to OneAPI). There are even individual pieces available now, and a good starting point is to look at [OneAPI Standalone Components](
https://software.intel.com/content/www/us/en/develop/articles/oneapi-standalone-components.html) (tools, libraries, compilers for Linux, Windows, and macOS). We will see how this plays out for "classic" vs. "next gen." compilers or DPC++ vs Fortran and friends, but at least Intel MKL seems to be a component that can be considered as "generally available" with some good will.

**Comment by hfp** [comment]
I am stuck with:

```text
Installing from scratch into /opt/cp2k-toolchain/install/libvdwxc-0.4.0
[91mERROR: (./scripts/stage7/install_libvdwxc.sh, line 83) Non-zero exit code detected.
[0mThe command '/bin/sh -c ./install_cp2k_toolchain.sh \
  --mpi-mode=mpich \
  --math-mode=mkl \
  --with-reflapack=no \
  --with-scalapack=no \
  --libint-lmax=${LIBINT_LMAX} \
  --gpu-ver=${GPU_VERSION} && \
rm -rf ./build' returned a non-zero code: 1
```

Is there a way to inspect artifacts like `configure.log` (`install_libvdwxc.sh`)?

**Comment by oschuett** [comment]
You can temporarily modify the install scripts to provide more output. There is also the old idea to make this a permanent feature (#433).

Furthermore, you can build the container locally (should also work without a GPU):

```shell
cd cp2k/tools/toolchain
docker build --build-arg LIBINT_LMAX=4  --build-arg GPU_VERSION=P100 -f Dockerfile.cuda_mkl .
```

**Comment by hfp** [comment]
The CP2K tool chain builds and installs libvdwxc despite of `--with-libvdwxc=no` as long as SIRIUS is enabled (although libvdwxc is supposedly optional for SIRIUS).

**Comment by dev-zero** [comment]
@hfp this will be fixed as part of #1517

**Comment by oschuett** [comment]
Just a heads up: I've made good progress on #1520 and will merge it tomorrow. If nothing new pops up then I'll do the release on Friday.

**Comment by hfp** [comment]
> @hfp this will be fixed as part of #1517

@dev-zero Thank you for the note! Main point of concern is about MKL and FFTW being mixed at link line (MKL seems to rule as libraries are put after fftw libraries). I will try to get some more information about claimed inconsistency if pfft or fftw3_mpi are mixed with MKL's fftw3 interface.

This PR drops FFTW library if MKL is present and if FFTW is not necessary otherwise (libvdwxc relies on native FFTW library). For cases where FFTW library and MKL are mixed, a new warning is issued by CP2K's toolchain.

**Pull request merged**
