### PR TITLE
Move do_regtest.py into tests dir

### PR DESCRIPTION
**Pull request by oschuett**
First step toward #2996.

### CODE REVIEW

**Comment by RMeli** [comment]
While you are at it, would you mind updating the following message on CMake?
https://github.com/cp2k/cp2k/blob/c94756ddc75c22fb829516d4d1ee9958f089b1c9/CMakeLists.txt#L1029

Otherwise I will do it later. Thanks.

**Comment by mtaillefumier** [comment]
i will do it in my open pr

**Comment by mtaillefumier** [comment]
@oschuett could you merge this one first then I can update mine with this change so there is no inconsistency between the two PRs.

**Comment by mtaillefumier** [comment]
thanks

**Pull request merged**
