### PR TITLE
[WIP] Backports for v6.1.1

### PR DESCRIPTION
**Pull request by dev-zero**

### CODE REVIEW

**Comment by oschuett** [comment]
The CI crashes because the `support/v6.1` branch has the old directory layout, i.e. `makefiles/Makefile`. Note, that the support branch does not require the tests to pass. So, you can just merge anyways.

**Comment by dev-zero** [comment]
@oschuett ok, thanks

**Comment by dev-zero** [comment]
@mkrack @juerghutter any other commits I should consider for a 6.1 backport?

**Comment by dev-zero** [comment]
closing due to lack of interest and impending release of 7.1

**Pull request closed without merging**
