### PR TITLE
Toolchain: Upgrade to ELPA 2022.05.001

### PR DESCRIPTION
**Pull request by oschuett**

### CODE REVIEW

**Comment by mtaillefumier** [comment]
you save me quite a lot of time with this PR. i cross my finger that this single update will solve the issues I have on cray systems at the moment.

**Comment by oschuett** [comment]
Fingers crossed :-)

**Comment by oschuett** [comment]
BTW, we're currently disabling OpenMP for ELPA on Cray machines (#1860). Perhaps, this upgrade also resolves that issue?

**Comment by mtaillefumier** [comment]
Unfortunately this update does not solve the issue I am observing on cray systems. I have a user input that triggers a series of mpi failure deep inside ELPA and cray-mpi. So it is difficult for me to test if the issue reported in #1860 is fixed until the cray mpi stack is working.

**Pull request merged**
