### PR TITLE
Speedup Spack build

### PR DESCRIPTION
**Pull request by RMeli**
Speedup Spack build by [generating depfiles](https://spack.readthedocs.io/en/latest/environments.html#generating-depfiles-from-environments).

### CODE REVIEW

**Comment by RMeli** [comment]
CMake action time down from 59m in https://github.com/cp2k/cp2k/pull/3143 to 49m. (Not sure how variable timings are though...)

**Comment by oschuett** [comment]
This is a nice speedup!

I wonder if `-j32` is maybe a bit too much since the individual package installations also use up to 32 jobs, don't they?

And as a nit, I notice that the output now contains weird characters:
```
[0m[91m==> 
```

**Comment by RMeli** [comment]
I had to [dig into the source code](https://spack.readthedocs.io/en/latest/_modules/spack/util/cpus.html#determine_number_of_jobs) to confirm what I've been told, but Spack uses `-j16` as default (or the number of CPUs, if lower). So `-j32` is where the speedup comes from. The documentation also says the following:
> Spack respects the Make jobserver and forwards it to the build environment of packages, meaning that a single -j flag is enough to control the load, even when packages are built in parallel.

> And as a nit, I notice that the output now contains weird characters

Good catch. I think this is related to colours, I'll look into it.

**Comment by RMeli** [comment]
Thanks. Looks like `SPACK_COLOR=never` didn't do the trick, I'll fix the weird characters on another PR, provably after the holidays.

**Pull request merged**
