### PR TITLE
improve element comparison in reftraj

### PR DESCRIPTION
**Pull request by BelizSertcan**
This PR addresses an issue where the REFTRAJ was raising errors due to potential aliasing in trajectory file that is created with [PRINT_ATOM_KIND](https://manual.cp2k.org/trunk/CP2K_INPUT/MOTION/PRINT/TRAJECTORY.html#CP2K_INPUT.MOTION.PRINT.TRAJECTORY.PRINT_ATOM_KIND) set to True. Previously, only the element symbol of the initial configuration was compared to the reftraj trajectory. Now the element kind of the reference is also compared.

The tests run smoothly, as well as my own calculations. However, there can be some unforeseen cases that are not covered by tests where this may fail.

### CODE REVIEW

**Comment by BelizSertcan** [comment]
How can I solve this slow test failure? It is not a file I created or modified.

**Comment by oschuett** [comment]
Don't worry, this is a false positive. I just restarted the test.

**Comment by BelizSertcan** [comment]
why does it happen?

**Comment by mkrack** [comment]
> why does it happen?

Mostly bad luck, I guess. It also happens to me often, e.g. today. Overall it is a kind of annoying.

**Comment by oschuett** [comment]
The runtimes of our tests are inherently noisy. The two main reasons are the parallelism in our [do_regtest.py](https://github.com/cp2k/cp2k/blob/master/tests/do_regtest.py) script and other cloud tenants. However, we're using a very generous criterion of `slow_test_threshold = 2 * percentile(timings, 0.95)`. So in principle all tests should be able to stay far away from the threshold.

> Overall it is a kind of annoying.

True. Maybe we should re-run directories with slow tests one more time before flagging them?

**Pull request merged**
