### PR TITLE
Longrange potential for MP2 and RPA

### PR DESCRIPTION
**Pull request by fstein93**
This PR enables ...
- ... longrange potentials for MP2 and RPA. It is a first step to enable range-separated double-hybrid functionals with range-separation within the correlation part.
- ... Eigenvalue decompositions as an alternative for the Cholesky decomposition in RI. (necessary for longrange potentials)
- ... lots of regtests.

Misc:
Refactoring and Splitting of some modules in the MP2 code

### CODE REVIEW

**Comment by oschuett** [comment]
Thanks for the refactoring the MP2 code. I saw that some of the new test are taking more than a minute to run. Maybe you could try to speed them up a bit?

**Comment by oschuett** [comment]
PS: I'm trying to get all all the regtests to run in less than 30s, see also #174.

**Comment by fstein93** [comment]
Ok, lets see whether they became fast enough.

**Comment by fstein93** [comment]
It seems that all RPA. MP2, GW, and Double hybrid tests run in less than 30 seconds. @oschuett  What do you think?

**Comment by oschuett** [comment]
Great! Thanks for going the extra mile :-)

**Pull request merged**
