### PR TITLE
S-ALMO patch

### PR DESCRIPTION
**Pull request by oschuett**
Fermi-Dirac smearing within the ALMO formalism, allowing an ALMO description of metals.
(contains also a quick fix for molecular guess with the diagonalisation algorithm, within ALMO)

Originally submitted as PR #18 .

### CODE REVIEW

**Comment by oschuett** [comment]
Your new regtest (`s-almo-no-deloc.inp`) takes 73 seconds to run. That's pretty long. Maybe there is a way to speed it up?

**Comment by RubenStaub** [comment]
On my machine it was reasonable (compared to other almo regtests).
I already tried to optimize its speed (metals are pretty hard to converge...) but I will see if I can reduce further the computational time without losing too much of the charge transfer effects that are being tested...

Thanks for the comment!

**Comment by oschuett** [comment]
Hi Ruben,

thanks for trimming the regtest. Yes, you can open a new PR, but make sure that your git history does not contain any merges. Alternatively, I can take care this evening. Now I have to run.

**Comment by RubenStaub** [comment]
That would be really kind of you, I must admit I am quite new to rebasing my commits...

Thanks again, and sorry for the trouble

**Comment by oschuett** [comment]
Wow, that test went down to 15.78 seconds. Good job!

Btw, the git hassle is my fault. In the meantime I changed the configuration. PR branches no longer need to be up to date. So, your next PR should go a lot smoother.

**Comment by alazzaro** [comment]
FYI, the tests are failing for the (look at the dashboard https://dashboard.cp2k.org/ )

**Comment by oschuett** [comment]
Yes, I saw it. @RubenStaub could you have a look?

**Pull request merged**
