### PR TITLE
HFX: Do not rely on block order of tensor iterator

### PR DESCRIPTION
**Pull request by oschuett**

### CODE REVIEW

**Comment by oschuett** [comment]
@JWilhelm and @abussy FYI: The new sparse matrix library will no longer iterate over the blocks in sorted order.

**Comment by JWilhelm** [comment]
> @JWilhelm and @abussy FYI: The new sparse matrix library will no longer iterate over the blocks in sorted order.

Thanks for letting us know, Ole. Do you have a feeling whether this change will have an impact on performance or memory consumption?

**Comment by oschuett** [comment]
This PR should not affect memory or performance, because the HFX code already kept a copy of the indices.

And so far I'm not aware of any other places that depend on the iteration order.

Dropping the block sorting will allow the new matrix library to have better OpenMP performance.

**Comment by JWilhelm** [comment]
> Dropping the block sorting will allow the new matrix library to have better OpenMP performance.

Sounds good!

**Comment by abussy** [comment]
> And so far I'm not aware of any other places that depend on the iteration order.

Neither do I. To be honest, I did not even realize the iterator followed a specific block order.

**Pull request merged**
