### PR TITLE
Doc Update for DFT Poisson Solvers

### PR DESCRIPTION
**Pull request by patrickmelix**
Adds descriptions to `%FORCE_EVAL%DFT%POISSON_SOLVER` keywords. Mainly stating the supported periodicity of the keywords. Found these through looking at the code and trial-error runs of the latest code. Therefore, please, someone who knows this part of the code better *double check the info* added. The respective page in the Wiki is extremely outdated.

Moved the description of the MT keyword from the subsection header to the keyword itself because it is here that the user would expect it in my opinion.

### CODE REVIEW

**Comment by oschuett** [comment]
Please run `make pretty` to fix the formatting.

**Comment by patrickmelix** [comment]
Sorry for these newbie problems... Is there an overview of all these little helpers? Doing it now...

**Comment by oschuett** [comment]
> Is there an overview of all these little helpers?

There is https://www.cp2k.org/dev:starting, but generally our documentation could probably use some more curation.
We try to make up for it by responding quickly to PRs :-)

**Comment by patrickmelix** [comment]
Ok, so learning by doing :+1:  Working on the documentation as you might have noticed :wink: 
Indeed, never seen such quick replies anywhere else! Thanks for the effort and your support.

**Pull request merged**
