### PR TITLE
Hybrid backend updates

### PR DESCRIPTION
**Pull request by mtaillefumier**
- Use dgemm inside integrate (ortho and generic cases)
- various changes and bug fixes when running with mpi.
- integrate works with or without the spherical cutoff (does not matter actually)

Some numbers about the performance of these backends. I used this input file (H2O-128), run the code on 4 threads 8 ranks on Xeon platform with full vectorization support, MKL and libxsmm (git version) 

```
&GLOBAL
  ECHO_ALL_HOSTS
  PROJECT H2O-128
  RUN_TYPE energy_force
  PRINT_LEVEL low
  &TIMINGS
     THRESHOLD 0.000001
  &END TIMINGS
  &GRID
     APPLY_CUTOFF TRUE
     BACKEND REF
     QUEUE_LENGTH 8192
&END
&END GLOBAL

&FORCE_EVAL
  METHOD QS
  &DFT
    BASIS_SET_FILE_NAME GTH_BASIS_SETS
    POTENTIAL_FILE_NAME POTENTIAL
    &MGRID
      CUTOFF 400
    &END MGRID
    &QS
      EPS_DEFAULT 1.0E-12
    &END QS
    &SCF
      EPS_SCF 1.0E-7
      MAX_SCF 21
      SCF_GUESS atomic
      &OT on
        MINIMIZER DIIS
      &END OT
      &OUTER_SCF on
        EPS_SCF 1.0E-7
      &END OUTER_SCF
      &PRINT
        &RESTART off
        &END RESTART
      &END PRINT
    &END SCF
    &XC
      &XC_FUNCTIONAL Pade
      &END XC_FUNCTIONAL
    &END XC
  &END DFT
  &PRINT
    &GRID_INFORMATION on
    &END GRID_INFORMATION
  &END PRINT
  &SUBSYS
    &CELL
      ABC 15.6404 15.6404 15.6404
      ALPHA_BETA_GAMMA 89.0 92.0 91.0
    &END CELL
    &COORD
   O       4.963362       8.433745       6.522726
   O       8.071195      10.247451      13.276063
   O      13.850862      12.652854      15.313528
   O      10.628770      14.045936      13.059901
   O       6.325463      12.328145       3.498946
   O       3.583600      12.446390       8.539707
   O      14.871126      15.358423       8.766155
   O      13.901523      10.863702       1.750201
   O      14.067166       0.862917       3.662820
   O      10.133858      15.114355       5.659292
   O      12.335899      11.027651      13.245276
   O      11.020881       3.916524       5.030404
   O       9.394684       6.531654       5.826834
   O      11.080390       7.885268       7.198950
   O       8.896688       8.249600       3.615318
   O       7.353156       1.137779       5.346406
   O      14.726780       7.918215      10.773641
   O       1.861458      11.989979       2.208095
   O       5.043121       6.543380       9.229162
   O       8.759694      11.116925       3.548469
   O       6.997656       8.373444       9.806165
   O       6.063005      12.809828       7.806901
   O      10.366591       5.779853       2.712706
   O       1.542969       4.767262      12.213947
   O      10.685570      14.507915       8.519941
   O      12.849421      13.198702       9.038657
   O       0.963120      14.402597      12.834647
   O       7.797670       4.829150      12.447033
   O       3.835427       3.788119      12.965881
   O       3.376860       4.479186       1.446663
   O       2.947460       1.489874       9.046559
   O       3.108796      14.723769       5.201095
   O      15.204514       8.599951       0.959433
   O      15.219684       4.238425      15.684030
   O       4.100649       1.057601       2.040112
   O      11.001052       2.229682      10.064311
   O       0.478278       0.949105       2.102755
   O      13.497545       5.548164      10.181923
   O       7.506276       1.277199       9.722916
   O       7.428299       4.380540       1.411980
   O       7.928952      14.363028       9.316256
   O       0.355839      11.996260      13.602596
   O      10.664734       7.760921      14.011072
   O       2.130951       6.397562       4.547882
   O       6.997688       7.117398      14.170903
   O       9.843852       1.807540       1.906473
   O       4.765738       9.146359       2.409067
   O       4.102297       1.274905       6.068037
   O      15.014340      11.743955       4.053518
   O      12.695114      13.021970       5.787211
   O      13.858302       3.507332       4.146316
   O       7.022070      10.109293       7.424303
   O       5.539291       5.159365       2.927469
   O       9.768643      11.517745      11.838411
   O      10.503632       1.060928      12.343495
   O       5.637836      14.137294       5.298814
   O      13.230577      15.494257      12.417538
   O      10.087712      12.367132       5.676113
   O       3.823444      11.248314       3.611973
   O       2.764628       9.932668      12.219621
   O       6.337327       1.214539      14.384465
   O       9.932541      13.322345       2.141626
   O       8.026468       1.856250      12.446566
   O      12.678267       4.212245       7.543967
   O      13.171058       4.494997       1.771265
   O       1.270597      13.402991       7.043142
   O       2.561666      15.503539      15.004783
   O       9.418846       5.882450       0.091388
   O      13.279532       8.467153      13.191095
   O      14.784685      10.103797       9.128104
   O       5.420783       3.626432      15.485019
   O       5.484596       2.586023       3.716333
   O      13.407464       7.649770       5.701169
   O      14.491627       2.828827      13.502603
   O       6.975558       5.474364       6.932584
   O       3.311237       6.301528       6.829047
   O       0.998842       3.600800       9.862514
   O       9.866483      10.306933       7.180898
   O       2.074137      10.679976      15.509320
   O      11.018416       9.906723       0.630304
   O       1.183950       1.843702       7.098684
   O      14.873704       5.527544       6.848733
   O       2.173299       7.943131       2.110457
   O       4.449383      11.930616      11.079086
   O       1.710425      14.756574      10.096897
   O       6.694784       0.922595       1.239003
   O       4.564438      11.918442      15.363533
   O       5.477639       4.707670      11.065326
   O      11.342444       0.223097       3.577043
   O       7.426077      12.972512      11.521810
   O      11.491853       1.563182       7.107076
   O       4.794353       4.113581       6.561312
   O      11.305735       3.619278       0.282229
   O       1.481140       5.957409       8.624482
   O       0.119546      10.931817       6.783795
   O       2.484663       6.791214      15.186771
   O      13.950657      12.916459      11.346835
   O       6.051702      14.320089      13.213208
   O       2.417817      14.602343       2.749723
   O       3.040699      10.496700       6.149311
   O       8.648120       3.218837       3.744312
   O       5.305757       2.668899       9.163911
   O       6.031135       7.542813       4.011356
   O      15.264572       0.530244      15.103544
   O       1.202379      11.443873      10.338401
   O      14.305770       2.092612      10.350492
   O       7.239758      12.387106      14.813865
   O       7.341353       9.684340       0.723854
   O       5.857541       9.676357      11.912006
   O      15.332365       7.094962      14.318822
   O      10.447327       8.207812       9.585339
   O       9.866363       4.445989      10.955351
   O      13.658983       0.219428       6.214705
   O       7.322356      13.965677       1.578063
   O       0.644540       4.039583       5.338294
   O      11.742745      10.899134       8.906616
   O       0.863237       3.520934       2.306355
   O      12.841333      10.018102       4.330247
   O       8.609050       2.288503       7.430427
   O      11.067694      12.559978      15.366360
   O      11.923672       3.212040      13.107757
   O      11.306237       6.632227      11.461951
   O      12.437417       7.860470       2.936097
   O       1.645609       7.437039      11.743266
   O      10.045665       4.639989       7.951130
   O       3.297915      13.397525      13.230354
   O       2.464454       1.557718      12.716823
   O       4.302185       8.124888      13.787389
   H       4.581468       7.718593       7.031593
   H       5.435252       7.997984       5.813033
   H       8.381737       9.538324      13.839031
   H       7.875012      10.964336      13.879239
   H      14.014609      12.142905      16.106856
   H      14.391871      12.234836      14.643601
   H      10.739569      13.533892      13.861004
   H      10.132364      13.472919      12.475551
   H       5.425531      12.003488       3.468104
   H       6.310811      13.012792       4.167733
   H       2.831114      13.037692       8.558619
   H       3.397989      11.844750       7.818728
   H      14.215688      14.710076       8.508709
   H      14.915685      15.962115       8.024669
   H      14.442896      10.979475       2.531061
   H      13.131333      10.387571       2.060586
   H      13.235552       0.480036       3.383444
   H      14.167503       0.581424       4.572175
   H       9.268459      15.423495       5.391430
   H      10.724909      15.435978       4.978521
   H      12.682383      11.900242      13.058822
   H      11.530377      10.974348      12.730956
   H      10.862047       3.493530       5.874252
   H      11.866334       3.570906       4.744068
   H      10.010906       6.860110       6.481524
   H       9.772826       5.701645       5.536446
   H      10.713257       8.747058       7.002065
   H      10.930529       7.769221       8.137196
   H       9.008071       7.846692       4.476416
   H       9.404635       7.694874       3.023287
   H       7.885169       1.417698       6.091281
   H       6.462912       1.407047       5.572662
   H      14.465524       8.122806      11.671483
   H      14.387942       7.036249      10.620165
   H       1.079976      11.549099       2.541476
   H       1.854266      11.812527       1.267515
   H       5.627954       7.254025       9.492195
   H       5.358566       6.280575       8.364489
   H       8.728012      10.160756       3.517346
   H       7.843327      11.389131       3.499416
   H       7.064983       9.034969       9.117627
   H       6.681536       8.854422      10.570991
   H       6.096247      13.255760       6.960573
   H       5.135401      12.812072       8.043075
   H      10.251809       4.879805       3.017615
   H      11.247569       6.019998       2.999828
   H       2.425379       4.423632      12.353605
   H       1.622138       5.706596      12.380127
   H      10.435334      14.464737       7.597038
   H       9.863861      14.392213       8.997057
   H      12.151749      13.846631       8.940295
   H      12.401656      12.354243       8.987406
   H       1.041376      14.716046      11.933616
   H       0.431193      15.065997      13.274178
   H       7.657165       5.609226      12.983662
   H       7.113550       4.871097      11.778862
   H       4.492907       4.226503      12.425723
   H       4.197120       3.813194      13.851760
   H       3.028991       5.174958       0.888880
   H       2.608925       4.123752       1.894070
   H       2.354380       1.561214       8.298628
   H       2.601814       2.111564       9.687076
   H       2.496453      14.284442       5.791230
   H       2.669671      14.716265       4.350599
   H      14.931000       9.483201       0.711861
   H      14.543448       8.311558       1.588759
   H      14.806603       3.662787      15.040418
   H      15.806913       4.791820      15.169104
   H       3.487941       1.365078       1.372072
   H       3.735668       0.223182       2.334673
   H      10.930358       1.492019      10.670189
   H      11.783438       2.701109      10.350422
   H       0.373431       0.943162       1.151333
   H      -0.331325       0.562024       2.435836
   H      13.328483       5.602953       9.241365
   H      13.904987       4.690509      10.302961
   H       7.979807       1.447145      10.537237
   H       7.699278       0.361971       9.519594
   H       7.879980       3.677583       1.878957
   H       6.921010       4.830270       2.087726
   H       7.276262      13.850239       8.839522
   H       7.900170      14.017994      10.208643
   H       0.566590      12.917379      13.449771
   H       0.097504      11.663383      12.743127
   H      10.275806       6.980124      14.405182
   H      10.496386       7.665796      13.073607
   H       2.563595       6.556361       3.708934
   H       1.500251       7.112689       4.631806
   H       7.206023       7.863029      13.607998
   H       6.088301       7.261122      14.432801
   H       9.059286       1.416705       1.521847
   H       9.511490       2.498088       2.479979
   H       5.181015       8.567468       3.048333
   H       3.954045       8.698238       2.171213
   H       3.323672       1.528105       6.563885
   H       3.866094       0.442374       5.658975
   H      14.146610      12.079728       4.278314
   H      15.272574      11.219653       4.811577
   H      12.716562      12.455880       6.558777
   H      11.770411      13.059590       5.542791
   H      14.153945       2.652228       3.833869
   H      13.419264       3.899892       3.391747
   H       6.656515      10.977596       7.255036
   H       6.361994       9.501768       7.090470
   H       4.712486       5.080316       2.451678
   H       5.521694       4.441294       3.560158
   H       9.189146      10.923676      12.315377
   H       9.179345      12.154039      11.433330
   H      10.671879       0.186135      12.693725
   H       9.549978       1.142946      12.350583
   H       4.689829      14.268322       5.317390
   H       5.985844      14.953053       4.938731
   H      12.546401      14.844149      12.257863
   H      12.876821      16.308055      12.058620
   H       9.756019      13.254250       5.814793
   H       9.607961      12.048315       4.911635
   H       3.064895      11.422889       3.054873
   H       4.291140      10.542078       3.166190
   H       2.001271      10.248909      12.702851
   H       2.907174      10.590416      11.538974
   H       5.648267       1.877288      14.431286
   H       6.585421       1.061461      15.296193
   H       9.740490      12.519628       2.626387
   H      10.584255      13.059982       1.491498
   H       7.455032       1.571433      13.159709
   H       7.941730       2.809647      12.437319
   H      13.106722       3.411333       7.241976
   H      13.240150       4.919265       7.226727
   H      12.368225       4.300614       1.287626
   H      13.862495       4.466405       1.109956
   H       0.601526      14.024395       7.330255
   H       0.816229      12.561332       7.005843
   H       2.606189      15.728879      14.075552
   H       1.751050      15.909700      15.311648
   H       8.495514       5.631109       0.068638
   H       9.589849       6.084955       1.011160
   H      13.316729       9.402787      13.389684
   H      12.379524       8.213880      13.396205
   H      13.918259      10.505485       9.192801
   H      14.676156       9.235384       9.515806
   H       6.242915       3.976825      15.827883
   H       4.811725       3.679161      16.221565
   H       5.094286       2.686336       4.584564
   H       4.898319       1.984198       3.257728
   H      13.959261       6.906132       5.943560
   H      12.760208       7.707487       6.403991
   H      14.969381       3.387665      12.889672
   H      13.602198       2.792224      13.150740
   H       7.679644       4.993292       7.367401
   H       7.415258       5.972883       6.243836
   H       3.810284       5.488758       6.747876
   H       2.838344       6.376576       6.000209
   H       1.201385       4.317435       9.261147
   H       1.095921       3.984260      10.734160
   H       8.983144       9.978931       7.349300
   H       9.731317      11.166458       6.781926
   H       2.882211      11.167225      15.348581
   H       1.472398      10.982022      14.828945
   H      10.205799       9.598641       1.031516
   H      11.290942       9.189004       0.058604
   H       0.558492       1.215423       6.737713
   H       1.132569       2.597863       6.511459
   H      15.392637       5.068030       6.188591
   H      15.494223       5.717274       7.552430
   H       1.359386       8.375518       1.851964
   H       2.491619       7.530928       1.307342
   H       3.930723      12.466553      11.679082
   H       4.127627      12.165120      10.208619
   H       1.031873      14.870889       9.431517
   H       2.312758      15.486507       9.953288
   H       6.898133       0.021480       1.489743
   H       5.806915       1.068076       1.565740
   H       4.879440      12.531428      16.027803
   H       5.343283      11.696347      14.853331
   H       5.304646       5.468144      10.510363
   H       5.487486       3.966167      10.460093
   H      10.682669       0.812386       3.211437
   H      11.375385      -0.510655       2.963240
   H       6.968873      13.462683      12.205132
   H       6.748898      12.423743      11.126193
   H      11.398639       1.428458       8.050152
   H      10.636236       1.331547       6.745834
   H       5.559402       4.680155       6.660940
   H       4.741233       3.634449       7.388260
   H      10.965383       2.838195       0.718466
   H      10.526206       4.126248       0.055186
   H       2.151544       6.183022       7.979588
   H       1.693196       6.493418       9.388654
   H      -0.065205      10.491692       7.613487
   H       0.934641      10.534254       6.477533
   H       1.612127       6.933760      14.819901
   H       3.084290       7.085600      14.501194
   H      14.370852      13.670525      11.760422
   H      13.655238      13.242663      10.496806
   H       5.117003      14.119782      13.262678
   H       6.094269      15.275850      13.243879
   H       1.684983      15.055245       2.332511
   H       2.318871      13.688619       2.482233
   H       3.301587      10.821578       5.287555
   H       3.569324       9.709332       6.279080
   H       9.402765       3.485324       4.269409
   H       8.068278       2.776805       4.364491
   H       5.849660       1.904585       9.354240
   H       4.458877       2.303173       8.908431
   H       5.856290       6.650150       3.713341
   H       6.956707       7.685055       3.813075
   H      14.578215      -0.136917      15.110099
   H      15.036706       1.101780      14.370293
   H       0.862260      12.331047      10.222329
   H       0.576388      10.884751       9.878239
   H      15.013369       2.687846      10.597944
   H      14.749248       1.349716       9.941024
   H       7.635604      12.750784      15.605874
   H       7.063281      13.149121      14.262122
   H       6.630981      10.323694       0.777061
   H       6.910682       8.837082       0.837471
   H       6.518696      10.163169      12.404063
   H       5.158628      10.311483      11.755901
   H      14.513415       7.228639      13.841660
   H      15.188680       7.517995      15.165361
   H      10.884896       7.694003      10.264136
   H       9.537008       8.263555       9.875929
   H      10.169920       3.541428      11.031858
   H       9.058984       4.472429      11.468839
   H      12.939998       0.748518       6.560183
   H      13.359162      -0.684568       6.310259
   H       6.806079      13.363518       2.113876
   H       8.230720      13.707514       1.734455
   H       1.376337       4.428271       4.859101
   H       0.026246       3.773603       4.657706
   H      11.202848      10.713245       9.674853
   H      11.207901      10.618858       8.163906
   H       0.837038       2.574495       2.447059
   H       0.139223       3.694244       1.704691
   H      13.344499       9.479144       4.940640
   H      12.047898      10.250105       4.812811
   H       8.179005       2.196707       8.280643
   H       8.921781       3.193061       7.416086
   H      11.996578      12.747212      15.501818
   H      11.029996      11.611989      15.239368
   H      11.753251       3.258077      14.048538
   H      11.376661       2.489403      12.799853
   H      10.727878       5.872638      11.392980
   H      12.187517       6.272930      11.359562
   H      12.694899       7.220715       3.599910
   H      12.399226       8.692890       3.407107
   H       1.995254       8.322850      11.839802
   H       0.706423       7.563149      11.608147
   H      10.003095       4.632780       8.907355
   H      10.980630       4.590207       7.752146
   H       3.257893      13.092363      14.136724
   H       2.487394      13.891684      13.107495
   H       2.594800       2.360087      13.222239
   H       3.067392       1.638961      11.977840
   H       4.204283       7.807066      12.889816
   H       4.120864       9.063058      13.730900
    &END COORD
    &KIND H
      BASIS_SET TZV2P-GTH
      POTENTIAL GTH-PADE-q1
    &END KIND
    &KIND O
      BASIS_SET TZV2P-GTH
      POTENTIAL GTH-PADE-q6
    &END KIND
  &END SUBSYS
&END FORCE_EVAL
```

orthorhombic case

| backend |         collocate        |            integrate |
| -------------| ------------------------  | --------------------- | 
|dgemm  (with cutoff) |             34.084 (48)       |       31.330 (48)|
|dgemm  (without cutoff) |             21.357 (48)  |            23.521 (48)|
|ref |                25.262 (48) |              27.588 (48)|

generic case (worst case scenario where the three directions are not orthogonal)

| backend |         collocate        |            integrate |
| -------------| ------------------------  | --------------------- | 
 | dgemm (no cutoff) |  83.599 (69) |             54.311 (69) |
| dgemm (with cutoff) | 106.486 (69)  |           77.227 (69) |
| ref |                104.120 (69) |             113.961 (69) |

### CODE REVIEW

**Comment by oschuett** [comment]
It's great that you got the integrate support ready in time. I'm still working on the GPU backend. Turns out the postprocessing is somewhat more complicated for integrate :-/

Unfortunately, I found a small problem in the current task list API, which I would like to fix first (#1222). Again, sorry for the late change. I only realized this yesterday.

**Comment by mtaillefumier** [comment]
On 12/15/20 3:41 PM, Ole Schütt wrote:

> It's great that you got the integrate support ready in time. I'm still
> working on the GPU backend. Turns out the postprocessing is somewhat
> more complicated for integrate :-/
>
CPU only right now. I have the integrate kernel but not the glue code.

Yes a lot of atomicAdd. I still scratch my head how to do this properly
(thinking of the AMD GPU as well). A local dgemm (on a thread block)
would help as well.

> Unfortunately, I found a small problem in the current task list API,
> which I would like to fix first (#1222
> <https://github.com/cp2k/cp2k/pull/1222>). Again, sorry for the late
> change. I only realized this yesterday.
>
It happens sometimes. Commit first then I will update although I do not
think it should interfere too much.

**Comment by dev-zero** [comment]
@mtaillefumier ready for merge?

**Comment by mtaillefumier** [comment]
Compilation fails with elpa. Not related to this PR.

**Comment by dev-zero** [comment]
> Compilation fails with elpa. Not related to this PR.

yes, I saw, seems to be a problem with ELPA+CUDA, possibly the same as in #1213 but it's an optional test anyway.
What I meant: it seems you rebased on top of #1222, is that the case and can we merge this?

**Comment by mtaillefumier** [comment]
Yes you can without any issues.

**Comment by dev-zero** [comment]
awesome, thanks!

**Pull request merged**
