### PR TITLE
Report realloc-lhs only as warning

### PR DESCRIPTION
**Pull request by mkrack**

### CODE REVIEW

**Comment by dev-zero** [comment]
I guess this will also need blacklisting in the conventions checker?

**Comment by oschuett** [comment]
The [compiler message](https://dashboard.cp2k.org/archive/mkrack-ssmp/commit_cf2ac326d85ff827c428a3723e964c44da7e5dcd.txt) says:

```
/data/user/krack/rt/gnu-ssmp/cp2k/src/core_ppl.F:641:46:

 !$OMP REDUCTION (+ : pv_thread, force_thread )
                                              1
Error: Code for reallocating the allocatable array at (1) will be added [-Werror=realloc-lhs]
```
Are we sure that this reallocation is really intended?

**Comment by mkrack** [comment]
Thanks @dev-zero, I forgot about the conventions checker. In that case it is presumably better to drop the -Wrealloc-lhs flag completely, since such warnings might pop up unexpectedly for any new commit.

**Comment by oschuett** [comment]
I think, we should just turn `force_thread` into a stack variable:
```
 REAL(KIND=dp), DIMENSION(3, SIZE(particle_set))    :: force_thread
```

**Comment by oschuett** [comment]
I think, we should keep `-Wrealloc-lhs` and continue to avoid automatic reallocations. This is one of those broken features in modern Fortran and that creates more problems than it solves.

**Comment by mkrack** [comment]
@oschuett That works.

**Comment by mkrack** [comment]
While natom is easily available via particle_set in the core_* routines, that is not the case in qs_overlap. It seems that we will have to pass natom explicitly which is a bit ugly.

**Comment by oschuett** [comment]
I guess, in that case going back to allocating a `POINTER` is the best solution.

**Comment by mkrack** [comment]
I tried that first, of course Unfortunately, pointer objects are not allowed in a reduction clause.

**Comment by oschuett** [comment]
@mkrack, sorry for the clever clogs. I didn't know that pointers don't work with `OMP REDUCTION`. I prepared #725 where I indeed created subroutines with the additional `natom` argument to make the arrays explicitly shaped.

I also opened #726 to discuss how we can better detect lhs-reallocs in the future.

**Comment by mkrack** [comment]
@oschuett I see you performed and committed already the interface changes which I have also in my local copy (could not commit them yesterday morning, since Merlin has maintenance until Monday). That duplication of work is a bit unfortunate.

**Comment by oschuett** [comment]
@mkrack I'm sorry. I didn't realize that you already had this prepared. I have not yet merged #725. So, feel free to close it. 

My main motivation was actually to check for roadblocks wrt. enabling OpenMP in `sdbg` and `pdbg`.

**Comment by mkrack** [comment]
@oschuett Please merge your changes.

**Pull request merged**
